-- 語彙サンプル（モックの101語）。本番ライブラリではありません。
-- Supabase SQL Editor に貼り付けて実行（0001_init.sql の後）。
insert into public.vocab_items (id, level, en, ja, type, theme) overriding system value values
  (1, '5', 'apple', 'りんご', 'word', 'たべもの'),
  (2, '5', 'milk', '牛乳', 'word', 'たべもの'),
  (3, '5', 'bread', 'パン', 'word', 'たべもの'),
  (4, '4', 'vegetable', '野菜', 'word', 'たべもの'),
  (5, '4', 'delicious', 'おいしい', 'word', 'たべもの'),
  (6, '4', 'have breakfast', '朝食をとる', 'phrase', 'たべもの'),
  (7, '3', 'dessert', 'デザート', 'word', 'たべもの'),
  (8, '3', 'a piece of cake', '朝飯前', 'idiom', 'たべもの'),
  (9, '5', 'dog', '犬', 'word', 'どうぶつ'),
  (10, '5', 'cat', 'ねこ', 'word', 'どうぶつ'),
  (11, '5', 'bird', '鳥', 'word', 'どうぶつ'),
  (12, '5', 'rabbit', 'うさぎ', 'word', 'どうぶつ'),
  (13, '5', 'elephant', 'ぞう', 'word', 'どうぶつ'),
  (14, '3', 'insect', '昆虫', 'word', 'どうぶつ'),
  (15, '4', 'walk the dog', '犬を散歩させる', 'phrase', 'どうぶつ'),
  (16, '3', 'raining cats and dogs', 'どしゃ降り', 'idiom', 'どうぶつ'),
  (17, '5', 'school', '学校', 'word', 'がっこう'),
  (18, '5', 'teacher', '先生', 'word', 'がっこう'),
  (19, '5', 'desk', '机', 'word', 'がっこう'),
  (20, '5', 'notebook', 'ノート', 'word', 'がっこう'),
  (21, '4', 'homework', '宿題', 'word', 'がっこう'),
  (22, '4', 'subject', '教科', 'word', 'がっこう'),
  (23, '5', 'go to school', '学校へ行く', 'phrase', 'がっこう'),
  (24, '4', 'be good at', '〜が得意だ', 'phrase', 'がっこう'),
  (25, '4', 'take a test', 'テストを受ける', 'phrase', 'がっこう'),
  (26, '3', 'graduate', '卒業する', 'word', 'がっこう'),
  (27, '4', 'library', '図書館', 'word', 'ばしょ'),
  (28, '4', 'station', '駅', 'word', 'ばしょ'),
  (29, '4', 'museum', '博物館', 'word', 'ばしょ'),
  (30, '4', 'restaurant', 'レストラン', 'word', 'ばしょ'),
  (31, '4', 'hospital', '病院', 'word', 'ばしょ'),
  (32, '5', 'next to', '〜のとなりに', 'phrase', 'ばしょ'),
  (33, '4', 'far from', '〜から遠い', 'phrase', 'ばしょ'),
  (34, '3', 'environment', '環境', 'word', 'ばしょ'),
  (35, '3', 'on the way to', '〜へ行く途中で', 'phrase', 'ばしょ'),
  (36, '5', 'red', '赤い', 'word', 'いろ・ようす'),
  (37, '5', 'blue', '青い', 'word', 'いろ・ようす'),
  (38, '5', 'big', '大きい', 'word', 'いろ・ようす'),
  (39, '5', 'small', '小さい', 'word', 'いろ・ようす'),
  (40, '4', 'beautiful', '美しい', 'word', 'いろ・ようす'),
  (41, '4', 'difficult', 'むずかしい', 'word', 'いろ・ようす'),
  (42, '4', 'dangerous', '危険な', 'word', 'いろ・ようす'),
  (43, '3', 'important', '重要な', 'word', 'いろ・ようす'),
  (44, '3', 'useful', '役に立つ', 'word', 'いろ・ようす'),
  (45, '5', 'run', '走る', 'word', 'うごき'),
  (46, '5', 'swim', '泳ぐ', 'word', 'うごき'),
  (47, '5', 'eat', '食べる', 'word', 'うごき'),
  (48, '4', 'visit', '訪ねる', 'word', 'うごき'),
  (49, '4', 'remember', '覚えている', 'word', 'うごき'),
  (50, '4', 'borrow', '借りる', 'word', 'うごき'),
  (51, '3', 'decide', '決める', 'word', 'うごき'),
  (52, '5', 'get up', '起きる', 'phrase', 'うごき'),
  (53, '5', 'look at', '〜を見る', 'phrase', 'うごき'),
  (54, '4', 'look for', '〜を探す', 'phrase', 'うごき'),
  (55, '3', 'take care of', '〜の世話をする', 'phrase', 'うごき'),
  (56, '3', 'look forward to', '〜を楽しみにする', 'phrase', 'うごき'),
  (57, '3', 'make friends with', '〜と友だちになる', 'phrase', 'うごき'),
  (58, '5', 'happy', 'うれしい', 'word', 'きもち'),
  (59, '5', 'sad', '悲しい', 'word', 'きもち'),
  (60, '5', 'tired', 'つかれた', 'word', 'きもち'),
  (61, '5', 'hungry', 'おなかがすいた', 'word', 'きもち'),
  (62, '4', 'excited', 'わくわくした', 'word', 'きもち'),
  (63, '3', 'be interested in', '〜に興味がある', 'phrase', 'きもち'),
  (64, '3', 'be afraid of', '〜をこわがる', 'phrase', 'きもち'),
  (65, '5', 'See you later', 'またね', 'idiom', 'かいわ'),
  (66, '5', 'Nice to meet you', 'はじめまして', 'idiom', 'かいわ'),
  (67, '5', 'How about you?', 'あなたはどう？', 'idiom', 'かいわ'),
  (68, '5', 'Thank you very much', 'どうもありがとう', 'idiom', 'かいわ'),
  (69, '4', 'Here you are', 'はい、どうぞ', 'idiom', 'かいわ'),
  (70, '4', 'Just a moment', 'ちょっと待って', 'idiom', 'かいわ'),
  (71, '4', 'Good luck', 'がんばって', 'idiom', 'かいわ'),
  (72, '3', 'Take it easy', '気楽にね', 'idiom', 'かいわ'),
  (73, '3', 'once in a while', 'ときどき', 'idiom', 'かいわ'),
  (74, '3', 'break a leg', 'がんばって（幸運を）', 'idiom', 'かいわ'),
  (75, 'p2', 'vegetarian', '菜食主義者', 'word', 'たべもの'),
  (76, 'p2', 'journey', '旅', 'word', 'ばしょ'),
  (77, 'p2', 'abroad', '海外へ', 'word', 'ばしょ'),
  (78, 'p2', 'appreciate', '感謝する', 'word', 'きもち'),
  (79, 'p2', 'recommend', 'すすめる', 'word', 'うごき'),
  (80, 'p2', 'be famous for', '〜で有名だ', 'phrase', 'いろ・ようす'),
  (81, 'p2', 'take part in', '〜に参加する', 'phrase', 'うごき'),
  (82, 'p2', 'by mistake', 'まちがって', 'phrase', 'かいわ'),
  (83, 'p2', 'It depends.', '場合による', 'idiom', 'かいわ'),
  (84, '2', 'agriculture', '農業', 'word', 'たべもの'),
  (85, '2', 'sustainable', '持続可能な', 'word', 'いろ・ようす'),
  (86, '2', 'achieve', '達成する', 'word', 'うごき'),
  (87, '2', 'reduce', '減らす', 'word', 'うごき'),
  (88, '2', 'curious', '好奇心の強い', 'word', 'きもち'),
  (89, '2', 'be responsible for', '〜に責任がある', 'phrase', 'がっこう'),
  (90, '2', 'come up with', '〜を思いつく', 'phrase', 'うごき'),
  (91, '2', 'as a result of', '〜の結果として', 'phrase', 'かいわ'),
  (92, '2', 'in the long run', '長い目で見れば', 'idiom', 'かいわ'),
  (93, 'p1', 'conservation', '保護', 'word', 'どうぶつ'),
  (94, 'p1', 'curriculum', '教育課程', 'word', 'がっこう'),
  (95, 'p1', 'inevitable', '避けられない', 'word', 'いろ・ようす'),
  (96, 'p1', 'hesitate', 'ためらう', 'word', 'きもち'),
  (97, 'p1', 'reluctant', '気が進まない', 'word', 'きもち'),
  (98, 'p1', 'sustain', '維持する', 'word', 'うごき'),
  (99, 'p1', 'bring about', '〜をもたらす', 'phrase', 'うごき'),
  (100, 'p1', 'take for granted', '〜を当然と思う', 'idiom', 'かいわ'),
  (101, 'p1', 'at the expense of', '〜を犠牲にして', 'idiom', 'かいわ')
on conflict (level, en) do nothing;

-- identity の採番を最大IDに合わせる
select setval(pg_get_serial_sequence('public.vocab_items','id'), (select max(id) from public.vocab_items));
