-- えいたんレーダー 初期スキーマ（v1）
-- 方針: Supabase Auth（保護者アカウント）+ RLS 必須。クライアントは anon key のみ。
-- 級コード: '5','4','3','p2'(準2級),'2','p1'(準1級)

-- ============================================================
-- 1. テーブル
-- ============================================================
create table public.children (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 30),
  created_at timestamptz not null default now()
);
create index children_parent_idx on public.children(parent_id);

create table public.vocab_items (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('5','4','3','p2','2','p1')),
  en text not null,
  ja text not null,
  type text not null check (type in ('word','phrase','idiom')),
  theme text not null,            -- 例: たべもの/どうぶつ/がっこう/ばしょ/いろ・ようす/うごき/きもち/かいわ（拡張可）
  example_en text,
  example_ja text,
  active boolean not null default true,
  unique (level, en)
);
create index vocab_level_idx on public.vocab_items(level) where active;

-- 回答ログ（1回答 = 1行）。週間集計・将来の分析の元データ。
create table public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null default now(),
  question_count int not null check (question_count > 0),
  correct_count int not null check (correct_count >= 0),
  duration_sec int not null default 0,
  by_mode jsonb not null default '{}'::jsonb   -- {"en2ja":[出題数,正解数], ...}
);
create index study_sessions_child_idx on public.study_sessions(child_id, started_at desc);

create table public.answer_logs (
  id bigint generated always as identity primary key,
  child_id uuid not null references public.children(id) on delete cascade,
  item_id bigint not null references public.vocab_items(id),
  mode text not null check (mode in ('en2ja','ja2en','spell')),
  correct boolean not null,
  session_id uuid references public.study_sessions(id) on delete set null,
  answered_at timestamptz not null default now()
);
create index answer_logs_child_time_idx on public.answer_logs(child_id, answered_at desc);
create index answer_logs_child_item_idx on public.answer_logs(child_id, item_id);

-- 累計集計（answer_logs の trigger で自動更新。クライアントは読み取りのみ）
create table public.item_stats (
  child_id uuid not null references public.children(id) on delete cascade,
  item_id bigint not null references public.vocab_items(id) on delete cascade,
  mode text not null check (mode in ('en2ja','ja2en','spell')),
  seen int not null default 0,
  correct int not null default 0,
  last_answered_at timestamptz,
  primary key (child_id, item_id, mode)
);

-- 級クリア（一度クリアしたら戻らない）
create table public.level_progress (
  child_id uuid not null references public.children(id) on delete cascade,
  level text not null check (level in ('5','4','3','p2','2','p1')),
  cleared_at timestamptz not null default now(),
  primary key (child_id, level)
);

-- 週間レポート設定
create table public.report_settings (
  child_id uuid primary key references public.children(id) on delete cascade,
  enabled boolean not null default true,
  email text,
  email_enabled boolean not null default true,
  line_enabled boolean not null default false,
  line_user_id text,
  dow smallint not null default 0 check (dow between 0 and 6),   -- 0=日曜 (JST)
  hour smallint not null default 19 check (hour between 6 and 22), -- JST
  timezone text not null default 'Asia/Tokyo',
  last_sent_at timestamptz,        -- 自動送信の最終時刻（二重送信防止）
  updated_at timestamptz not null default now()
);

create table public.report_logs (
  id bigint generated always as identity primary key,
  child_id uuid not null references public.children(id) on delete cascade,
  kind text not null check (kind in ('auto','manual')),
  channel text not null check (channel in ('email','line')),
  status text not null check (status in ('sent','failed')),
  error text,
  created_at timestamptz not null default now()
);
create index report_logs_child_idx on public.report_logs(child_id, created_at desc);

-- LINE 連携コード（作成は RPC、消費は line-webhook のみ）
create table public.line_link_codes (
  code text primary key,
  child_id uuid not null references public.children(id) on delete cascade,
  expires_at timestamptz not null,
  used_at timestamptz
);

-- AI 呼び出しの1日上限管理（Edge Function のみ）
create table public.ai_usage (
  child_id uuid not null references public.children(id) on delete cascade,
  day date not null,
  kind text not null,
  count int not null default 0,
  primary key (child_id, day, kind)
);

-- ============================================================
-- 2. 関数
-- ============================================================
create or replace function public.owns_child(p_child uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.children where id = p_child and parent_id = auth.uid());
$$;

-- answer_logs への insert で item_stats を更新
create or replace function public.bump_item_stats()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.item_stats (child_id, item_id, mode, seen, correct, last_answered_at)
  values (new.child_id, new.item_id, new.mode, 1, case when new.correct then 1 else 0 end, new.answered_at)
  on conflict (child_id, item_id, mode) do update
    set seen = public.item_stats.seen + 1,
        correct = public.item_stats.correct + excluded.correct,
        last_answered_at = greatest(public.item_stats.last_answered_at, excluded.last_answered_at);
  return new;
end $$;

create trigger answer_logs_bump_stats
after insert on public.answer_logs
for each row execute function public.bump_item_stats();

-- 級ごとの集計: n=語数, seen3=3回以上こたえた語数, attempts/correct=全形式の合計
create or replace function public.level_stat(p_child uuid, p_level text)
returns table (n int, seen3 int, attempts int, correct int)
language sql stable set search_path = public as $$
  with v as (select id from public.vocab_items where level = p_level and active),
  s as (
    select item_id, sum(seen) as seen, sum(correct) as correct
    from public.item_stats where child_id = p_child group by item_id
  )
  select
    (select count(*) from v)::int,
    (select count(*) from v join s on s.item_id = v.id where s.seen >= 3)::int,
    coalesce((select sum(s.seen) from v join s on s.item_id = v.id), 0)::int,
    coalesce((select sum(s.correct) from v join s on s.item_id = v.id), 0)::int;
$$;

-- クリア判定: 全語を3回以上こたえ、かつ正答率90%以上。下の級から順に判定し、新しくクリアした級を返す。
create or replace function public.sync_level_progress(p_child uuid)
returns text[] language plpgsql security definer set search_path = public as $$
declare
  lv text; st record; newly text[] := '{}';
begin
  if not public.owns_child(p_child) then raise exception 'forbidden'; end if;
  foreach lv in array array['5','4','3','p2','2','p1'] loop
    if exists (select 1 from public.level_progress where child_id = p_child and level = lv) then continue; end if;
    select * into st from public.level_stat(p_child, lv);
    if st.n > 0 and st.seen3 = st.n and st.attempts > 0 and st.correct::numeric / st.attempts >= 0.9 then
      insert into public.level_progress (child_id, level) values (p_child, lv);
      newly := newly || lv;
    else
      exit;
    end if;
  end loop;
  return newly;
end $$;

-- クイズ1回分をまとめて保存（セッション + 回答ログ + クリア判定）
-- p_answers: [{"item_id":1,"mode":"en2ja","correct":true}, ...]（最大100件）
create or replace function public.submit_session(p_child uuid, p_started timestamptz, p_answers jsonb)
returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  sid uuid; n int; c int; bm jsonb; newly text[];
begin
  if jsonb_typeof(p_answers) <> 'array' or jsonb_array_length(p_answers) = 0 or jsonb_array_length(p_answers) > 100 then
    raise exception 'invalid answers';
  end if;
  select count(*), count(*) filter (where (a->>'correct')::boolean)
    into n, c from jsonb_array_elements(p_answers) a;
  select coalesce(jsonb_object_agg(t.mode, jsonb_build_array(t.cnt, t.ok)), '{}'::jsonb) into bm
  from (
    select a->>'mode' as mode, count(*) as cnt, count(*) filter (where (a->>'correct')::boolean) as ok
    from jsonb_array_elements(p_answers) a group by 1
  ) t;
  insert into public.study_sessions (child_id, started_at, question_count, correct_count, duration_sec, by_mode)
  values (p_child, p_started, n, c,
          least(1800, greatest(0, extract(epoch from (now() - p_started))::int)), bm)
  returning id into sid;
  insert into public.answer_logs (child_id, item_id, mode, correct, session_id)
  select p_child, (a->>'item_id')::bigint, a->>'mode', (a->>'correct')::boolean, sid
  from jsonb_array_elements(p_answers) a;
  newly := public.sync_level_progress(p_child);
  return jsonb_build_object('session_id', sid, 'newly_cleared', to_jsonb(newly));
end $$;

-- 直近7日 / その前の7日の学習サマリ（週間レポート用）
create or replace function public.weekly_summary(p_child uuid, p_end date, p_tz text default 'Asia/Tokyo')
returns jsonb language sql stable set search_path = public as $$
  with s as (
    select (started_at at time zone p_tz)::date as d, question_count as q, correct_count as c, duration_sec as sec, by_mode
    from public.study_sessions
    where child_id = p_child and (started_at at time zone p_tz)::date between p_end - 13 and p_end
  ),
  tw as (select * from s where d >= p_end - 6),
  lw as (select * from s where d < p_end - 6),
  days as (select (p_end - g)::date as d from generate_series(0, 6) g)
  select jsonb_build_object(
    'period', jsonb_build_object('from', p_end - 6, 'to', p_end),
    'thisWeek', (select jsonb_build_object('days', count(distinct d), 'questions', coalesce(sum(q),0), 'correct', coalesce(sum(c),0), 'seconds', coalesce(sum(sec),0)) from tw),
    'lastWeek', (select jsonb_build_object('days', count(distinct d), 'questions', coalesce(sum(q),0), 'correct', coalesce(sum(c),0), 'seconds', coalesce(sum(sec),0)) from lw),
    'daily', (select jsonb_agg(jsonb_build_object('date', days.d, 'questions', coalesce((select sum(q) from tw where tw.d = days.d), 0)) order by days.d) from days),
    'byMode', (
      select coalesce(jsonb_object_agg(t.mode, jsonb_build_object('n', t.n, 'c', t.ok)), '{}'::jsonb)
      from (
        select m.key as mode, sum((m.value->>0)::int) as n, sum((m.value->>1)::int) as ok
        from tw, jsonb_each(tw.by_mode) m group by 1
      ) t
    )
  );
$$;

-- 「いま気になるところ」: 苦手マス（テーマ×形式, 6回以上）と、まちがいが多い語ワースト3（3回以上）
create or replace function public.weak_overview(p_child uuid)
returns jsonb language sql stable set search_path = public as $$
  with cells as (
    select v.theme, i.mode, sum(i.seen) as s, sum(i.correct) as c
    from public.item_stats i join public.vocab_items v on v.id = i.item_id
    where i.child_id = p_child group by 1, 2 having sum(i.seen) >= 6
  ),
  weak as (
    select theme, mode, s::int as attempts, round(100.0 * c / s)::int as accuracy
    from cells order by c::numeric / s asc limit 1
  ),
  words as (
    select v.en, v.ja, round(100.0 * sum(i.correct) / sum(i.seen))::int as accuracy
    from public.item_stats i join public.vocab_items v on v.id = i.item_id
    where i.child_id = p_child group by v.id, v.en, v.ja having sum(i.seen) >= 3
    order by sum(i.correct)::numeric / sum(i.seen) asc, v.en limit 3
  )
  select jsonb_build_object(
    'weakestCell', (select to_jsonb(weak) from weak),
    'worstWords', (select coalesce(jsonb_agg(to_jsonb(words)), '[]'::jsonb) from words)
  );
$$;

-- LINE 連携コードの発行（6桁・10分有効）
create or replace function public.create_line_code(p_child uuid)
returns text language plpgsql security definer set search_path = public as $$
declare c text; tries int := 0;
begin
  if not public.owns_child(p_child) then raise exception 'forbidden'; end if;
  delete from public.line_link_codes where child_id = p_child and used_at is null;
  loop
    c := lpad((floor(random() * 1000000))::int::text, 6, '0');
    begin
      insert into public.line_link_codes (code, child_id, expires_at) values (c, p_child, now() + interval '10 minutes');
      return c;
    exception when unique_violation then
      tries := tries + 1;
      if tries > 10 then raise exception 'could not allocate code'; end if;
    end;
  end loop;
end $$;

revoke all on function public.sync_level_progress(uuid) from public, anon;
revoke all on function public.create_line_code(uuid) from public, anon;
grant execute on function public.sync_level_progress(uuid) to authenticated;
grant execute on function public.create_line_code(uuid) to authenticated;

-- ============================================================
-- 3. RLS
-- ============================================================
alter table public.children        enable row level security;
alter table public.vocab_items     enable row level security;
alter table public.study_sessions  enable row level security;
alter table public.answer_logs     enable row level security;
alter table public.item_stats      enable row level security;
alter table public.level_progress  enable row level security;
alter table public.report_settings enable row level security;
alter table public.report_logs     enable row level security;
alter table public.line_link_codes enable row level security;   -- ポリシーなし = クライアントから不可
alter table public.ai_usage        enable row level security;   -- ポリシーなし = クライアントから不可

create policy children_all on public.children
  for all to authenticated using (parent_id = auth.uid()) with check (parent_id = auth.uid());

create policy vocab_read on public.vocab_items
  for select to authenticated using (true);

create policy sessions_select on public.study_sessions
  for select to authenticated using (public.owns_child(child_id));
create policy sessions_insert on public.study_sessions
  for insert to authenticated with check (public.owns_child(child_id));

create policy answers_select on public.answer_logs
  for select to authenticated using (public.owns_child(child_id));
create policy answers_insert on public.answer_logs
  for insert to authenticated with check (public.owns_child(child_id));

create policy stats_select on public.item_stats
  for select to authenticated using (public.owns_child(child_id));

create policy progress_select on public.level_progress
  for select to authenticated using (public.owns_child(child_id));

create policy report_settings_select on public.report_settings
  for select to authenticated using (public.owns_child(child_id));
create policy report_settings_insert on public.report_settings
  for insert to authenticated with check (public.owns_child(child_id));
create policy report_settings_update on public.report_settings
  for update to authenticated using (public.owns_child(child_id)) with check (public.owns_child(child_id));

create policy report_logs_select on public.report_logs
  for select to authenticated using (public.owns_child(child_id));

-- クライアントから書き換えさせない列（line_user_id / last_sent_at）は列権限で制限
revoke insert, update on public.report_settings from authenticated;
grant insert (child_id, enabled, email, email_enabled, line_enabled, dow, hour) on public.report_settings to authenticated;
grant update (enabled, email, email_enabled, line_enabled, dow, hour, updated_at) on public.report_settings to authenticated;

-- anon（未ログイン）には何も許可しない
-- ※ Supabase プロジェクトを bpulse-check（bp_records / bp_profile）と共用するため、対象を本アプリのテーブルに限定する
revoke all on table
  public.children, public.vocab_items, public.study_sessions, public.answer_logs,
  public.item_stats, public.level_progress, public.report_settings, public.report_logs,
  public.line_link_codes, public.ai_usage
from anon;
