-- 5級の語彙（537語）。scripts/vocab/build-seed.mjs で vocab_5.tsv から生成。手で編集しない。
-- 単語の選定は CEFR-J Wordlist Version 1.6（東京外国語大学投野由紀夫研究室）を元にしている。
-- Supabase の SQL Editor で実行する。同じ (level, en) があれば内容を上書きし、id は変えない（記録を壊さない）。
begin;
-- 動作確認用のサンプル（id 1〜101）は使わない。同じ語は下の insert で有効に戻る
update public.vocab_items set active = false where id between 1 and 101;
insert into public.vocab_items (level, en, ja, type, theme, example_en, example_ja, active) values
  ('5', 'apple', 'りんご', 'word', 'たべもの', null, null, true),
  ('5', 'banana', 'バナナ', 'word', 'たべもの', null, null, true),
  ('5', 'bread', 'パン', 'word', 'たべもの', null, null, true),
  ('5', 'breakfast', '朝ごはん', 'word', 'たべもの', null, null, true),
  ('5', 'lunch', '昼ごはん', 'word', 'たべもの', null, null, true),
  ('5', 'dinner', '夕ごはん', 'word', 'たべもの', null, null, true),
  ('5', 'cake', 'ケーキ', 'word', 'たべもの', null, null, true),
  ('5', 'candy', 'あめ', 'word', 'たべもの', null, null, true),
  ('5', 'cheese', 'チーズ', 'word', 'たべもの', null, null, true),
  ('5', 'chicken', 'とり肉', 'word', 'たべもの', null, null, true),
  ('5', 'chocolate', 'チョコレート', 'word', 'たべもの', null, null, true),
  ('5', 'cookie', 'クッキー', 'word', 'たべもの', null, null, true),
  ('5', 'corn', 'とうもろこし', 'word', 'たべもの', null, null, true),
  ('5', 'egg', 'たまご', 'word', 'たべもの', null, null, true),
  ('5', 'food', '食べ物', 'word', 'たべもの', null, null, true),
  ('5', 'fruit', 'くだもの', 'word', 'たべもの', null, null, true),
  ('5', 'grape', 'ぶどう', 'word', 'たべもの', null, null, true),
  ('5', 'hamburger', 'ハンバーガー', 'word', 'たべもの', null, null, true),
  ('5', 'ice cream', 'アイスクリーム', 'word', 'たべもの', null, null, true),
  ('5', 'juice', 'ジュース', 'word', 'たべもの', null, null, true),
  ('5', 'meat', '肉', 'word', 'たべもの', null, null, true),
  ('5', 'milk', '牛乳', 'word', 'たべもの', null, null, true),
  ('5', 'orange', 'オレンジ', 'word', 'たべもの', null, null, true),
  ('5', 'pizza', 'ピザ', 'word', 'たべもの', null, null, true),
  ('5', 'potato', 'じゃがいも', 'word', 'たべもの', null, null, true),
  ('5', 'rice', 'ごはん、米', 'word', 'たべもの', null, null, true),
  ('5', 'salad', 'サラダ', 'word', 'たべもの', null, null, true),
  ('5', 'sandwich', 'サンドイッチ', 'word', 'たべもの', null, null, true),
  ('5', 'soup', 'スープ', 'word', 'たべもの', null, null, true),
  ('5', 'sugar', 'さとう', 'word', 'たべもの', null, null, true),
  ('5', 'tea', 'お茶、紅茶', 'word', 'たべもの', null, null, true),
  ('5', 'tomato', 'トマト', 'word', 'たべもの', null, null, true),
  ('5', 'vegetable', '野菜', 'word', 'たべもの', null, null, true),
  ('5', 'water', '水', 'word', 'たべもの', null, null, true),
  ('5', 'coffee', 'コーヒー', 'word', 'たべもの', null, null, true),
  ('5', 'butter', 'バター', 'word', 'たべもの', null, null, true),
  ('5', 'yogurt', 'ヨーグルト', 'word', 'たべもの', null, null, true),
  ('5', 'cup', 'カップ、茶わん', 'word', 'たべもの', null, null, true),
  ('5', 'dish', '皿、料理', 'word', 'たべもの', null, null, true),
  ('5', 'animal', '動物', 'word', 'どうぶつ', null, null, true),
  ('5', 'bear', 'くま', 'word', 'どうぶつ', null, null, true),
  ('5', 'bird', '鳥', 'word', 'どうぶつ', null, null, true),
  ('5', 'cat', 'ねこ', 'word', 'どうぶつ', null, null, true),
  ('5', 'cow', '牛', 'word', 'どうぶつ', null, null, true),
  ('5', 'dog', '犬', 'word', 'どうぶつ', null, null, true),
  ('5', 'fish', '魚', 'word', 'どうぶつ', null, null, true),
  ('5', 'frog', 'かえる', 'word', 'どうぶつ', null, null, true),
  ('5', 'horse', '馬', 'word', 'どうぶつ', null, null, true),
  ('5', 'lion', 'ライオン', 'word', 'どうぶつ', null, null, true),
  ('5', 'monkey', 'さる', 'word', 'どうぶつ', null, null, true),
  ('5', 'mouse', 'ねずみ', 'word', 'どうぶつ', null, null, true),
  ('5', 'pet', 'ペット', 'word', 'どうぶつ', null, null, true),
  ('5', 'pig', 'ぶた', 'word', 'どうぶつ', null, null, true),
  ('5', 'rabbit', 'うさぎ', 'word', 'どうぶつ', null, null, true),
  ('5', 'sheep', 'ひつじ', 'word', 'どうぶつ', null, null, true),
  ('5', 'snake', 'へび', 'word', 'どうぶつ', null, null, true),
  ('5', 'tiger', 'トラ', 'word', 'どうぶつ', null, null, true),
  ('5', 'bee', 'ハチ', 'word', 'どうぶつ', null, null, true),
  ('5', 'butterfly', 'チョウ', 'word', 'どうぶつ', null, null, true),
  ('5', 'family', '家族', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'father', '父', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'mother', '母', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'brother', '兄、弟', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'sister', '姉、妹', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'grandfather', '祖父、おじいさん', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'grandmother', '祖母、おばあさん', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'dad', 'お父さん', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'mom', 'お母さん', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'baby', '赤ちゃん', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'boy', '男の子', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'girl', '女の子', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'child', '子ども', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'man', '男の人', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'woman', '女の人', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'friend', '友だち', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'people', '人々', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'uncle', 'おじ', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'aunt', 'おば', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'cousin', 'いとこ', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'son', '息子', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'daughter', '娘', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'doctor', '医者', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'nurse', '看護師', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'teacher', '先生', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'student', '生徒、学生', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'classmate', 'クラスメート', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'driver', '運転手', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'singer', '歌手', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'player', '選手', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'farmer', '農家の人', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'name', '名前', 'word', 'かぞく・ひと', null, null, true),
  ('5', 'arm', 'うで', 'word', 'からだ', null, null, true),
  ('5', 'body', '体', 'word', 'からだ', null, null, true),
  ('5', 'ear', '耳', 'word', 'からだ', null, null, true),
  ('5', 'eye', '目', 'word', 'からだ', null, null, true),
  ('5', 'face', '顔', 'word', 'からだ', null, null, true),
  ('5', 'hair', 'かみの毛', 'word', 'からだ', null, null, true),
  ('5', 'hand', '手', 'word', 'からだ', null, null, true),
  ('5', 'head', '頭', 'word', 'からだ', null, null, true),
  ('5', 'leg', 'あし（足のつけねから下）', 'word', 'からだ', null, null, true),
  ('5', 'mouth', '口', 'word', 'からだ', null, null, true),
  ('5', 'nose', '鼻', 'word', 'からだ', null, null, true),
  ('5', 'tooth', '歯', 'word', 'からだ', null, null, true),
  ('5', 'neck', '首', 'word', 'からだ', null, null, true),
  ('5', 'shoulder', 'かた', 'word', 'からだ', null, null, true),
  ('5', 'knee', 'ひざ', 'word', 'からだ', null, null, true),
  ('5', 'morning', '朝', 'word', 'じかん', null, null, true),
  ('5', 'afternoon', '午後', 'word', 'じかん', null, null, true),
  ('5', 'evening', '夕方', 'word', 'じかん', null, null, true),
  ('5', 'night', '夜', 'word', 'じかん', null, null, true),
  ('5', 'day', '日', 'word', 'じかん', null, null, true),
  ('5', 'week', '週', 'word', 'じかん', null, null, true),
  ('5', 'weekend', '週末', 'word', 'じかん', null, null, true),
  ('5', 'month', '（1か）月', 'word', 'じかん', null, null, true),
  ('5', 'year', '年', 'word', 'じかん', null, null, true),
  ('5', 'today', '今日', 'word', 'じかん', null, null, true),
  ('5', 'tomorrow', '明日', 'word', 'じかん', null, null, true),
  ('5', 'yesterday', 'きのう', 'word', 'じかん', null, null, true),
  ('5', 'time', '時間', 'word', 'じかん', null, null, true),
  ('5', 'hour', '1時間', 'word', 'じかん', null, null, true),
  ('5', 'minute', '分', 'word', 'じかん', null, null, true),
  ('5', 'birthday', '誕生日', 'word', 'じかん', null, null, true),
  ('5', 'holiday', '休日', 'word', 'じかん', null, null, true),
  ('5', 'now', '今', 'word', 'じかん', null, null, true),
  ('5', 'o''clock', '〜時（ちょうど）', 'word', 'じかん', null, null, true),
  ('5', 'Sunday', '日曜日', 'word', 'じかん', null, null, true),
  ('5', 'Monday', '月曜日', 'word', 'じかん', null, null, true),
  ('5', 'Tuesday', '火曜日', 'word', 'じかん', null, null, true),
  ('5', 'Wednesday', '水曜日', 'word', 'じかん', null, null, true),
  ('5', 'Thursday', '木曜日', 'word', 'じかん', null, null, true),
  ('5', 'Friday', '金曜日', 'word', 'じかん', null, null, true),
  ('5', 'Saturday', '土曜日', 'word', 'じかん', null, null, true),
  ('5', 'January', '1月', 'word', 'じかん', null, null, true),
  ('5', 'February', '2月', 'word', 'じかん', null, null, true),
  ('5', 'March', '3月', 'word', 'じかん', null, null, true),
  ('5', 'April', '4月', 'word', 'じかん', null, null, true),
  ('5', 'May', '5月', 'word', 'じかん', null, null, true),
  ('5', 'June', '6月', 'word', 'じかん', null, null, true),
  ('5', 'July', '7月', 'word', 'じかん', null, null, true),
  ('5', 'August', '8月', 'word', 'じかん', null, null, true),
  ('5', 'September', '9月', 'word', 'じかん', null, null, true),
  ('5', 'October', '10月', 'word', 'じかん', null, null, true),
  ('5', 'November', '11月', 'word', 'じかん', null, null, true),
  ('5', 'December', '12月', 'word', 'じかん', null, null, true),
  ('5', 'spring', '春', 'word', 'じかん', null, null, true),
  ('5', 'summer', '夏', 'word', 'じかん', null, null, true),
  ('5', 'autumn', '秋', 'word', 'じかん', null, null, true),
  ('5', 'winter', '冬', 'word', 'じかん', null, null, true),
  ('5', 'one', '1', 'word', 'かず', null, null, true),
  ('5', 'two', '2', 'word', 'かず', null, null, true),
  ('5', 'three', '3', 'word', 'かず', null, null, true),
  ('5', 'four', '4', 'word', 'かず', null, null, true),
  ('5', 'five', '5', 'word', 'かず', null, null, true),
  ('5', 'six', '6', 'word', 'かず', null, null, true),
  ('5', 'seven', '7', 'word', 'かず', null, null, true),
  ('5', 'eight', '8', 'word', 'かず', null, null, true),
  ('5', 'nine', '9', 'word', 'かず', null, null, true),
  ('5', 'ten', '10', 'word', 'かず', null, null, true),
  ('5', 'eleven', '11', 'word', 'かず', null, null, true),
  ('5', 'twelve', '12', 'word', 'かず', null, null, true),
  ('5', 'thirteen', '13', 'word', 'かず', null, null, true),
  ('5', 'fourteen', '14', 'word', 'かず', null, null, true),
  ('5', 'fifteen', '15', 'word', 'かず', null, null, true),
  ('5', 'sixteen', '16', 'word', 'かず', null, null, true),
  ('5', 'seventeen', '17', 'word', 'かず', null, null, true),
  ('5', 'eighteen', '18', 'word', 'かず', null, null, true),
  ('5', 'nineteen', '19', 'word', 'かず', null, null, true),
  ('5', 'twenty', '20', 'word', 'かず', null, null, true),
  ('5', 'thirty', '30', 'word', 'かず', null, null, true),
  ('5', 'forty', '40', 'word', 'かず', null, null, true),
  ('5', 'fifty', '50', 'word', 'かず', null, null, true),
  ('5', 'sixty', '60', 'word', 'かず', null, null, true),
  ('5', 'seventy', '70', 'word', 'かず', null, null, true),
  ('5', 'eighty', '80', 'word', 'かず', null, null, true),
  ('5', 'ninety', '90', 'word', 'かず', null, null, true),
  ('5', 'red', '赤い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'blue', '青い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'yellow', '黄色い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'green', '緑の', 'word', 'いろ・ようす', null, null, true),
  ('5', 'black', '黒い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'white', '白い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'brown', '茶色の', 'word', 'いろ・ようす', null, null, true),
  ('5', 'pink', 'ピンクの', 'word', 'いろ・ようす', null, null, true),
  ('5', 'purple', 'むらさきの', 'word', 'いろ・ようす', null, null, true),
  ('5', 'gray', '灰色の', 'word', 'いろ・ようす', null, null, true),
  ('5', 'big', '大きい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'small', '小さい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'long', '長い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'short', '短い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'tall', '背が高い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'new', '新しい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'old', '古い、年をとった', 'word', 'いろ・ようす', null, null, true),
  ('5', 'young', '若い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'hot', '暑い、熱い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'cold', '寒い、冷たい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'warm', 'あたたかい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'cool', 'すずしい、かっこいい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'good', 'よい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'bad', '悪い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'nice', 'すてきな', 'word', 'いろ・ようす', null, null, true),
  ('5', 'beautiful', '美しい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'pretty', 'きれいな', 'word', 'いろ・ようす', null, null, true),
  ('5', 'cute', 'かわいい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'fast', '速い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'slow', 'おそい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'easy', 'かんたんな', 'word', 'いろ・ようす', null, null, true),
  ('5', 'difficult', 'むずかしい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'high', '高い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'heavy', '重い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'busy', 'いそがしい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'free', 'ひまな、自由な', 'word', 'いろ・ようす', null, null, true),
  ('5', 'clean', '清潔な', 'word', 'いろ・ようす', null, null, true),
  ('5', 'dirty', 'よごれた', 'word', 'いろ・ようす', null, null, true),
  ('5', 'delicious', 'とてもおいしい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'sweet', 'あまい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'famous', '有名な', 'word', 'いろ・ようす', null, null, true),
  ('5', 'favorite', 'いちばん好きな', 'word', 'いろ・ようす', null, null, true),
  ('5', 'great', 'すごい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'wonderful', 'すばらしい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'dark', '暗い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'bright', '明るい', 'word', 'いろ・ようす', null, null, true),
  ('5', 'quiet', '静かな', 'word', 'いろ・ようす', null, null, true),
  ('5', 'strong', '強い', 'word', 'いろ・ようす', null, null, true),
  ('5', 'rich', 'お金持ちの', 'word', 'いろ・ようす', null, null, true),
  ('5', 'interesting', 'おもしろい（興味深い）', 'word', 'いろ・ようす', null, null, true),
  ('5', 'funny', 'おかしい（笑える）', 'word', 'いろ・ようす', null, null, true),
  ('5', 'exciting', 'わくわくさせる', 'word', 'いろ・ようす', null, null, true),
  ('5', 'fine', '元気な、晴れた', 'word', 'いろ・ようす', null, null, true),
  ('5', 'ready', '用意ができた', 'word', 'いろ・ようす', null, null, true),
  ('5', 'right', '正しい、右の', 'word', 'いろ・ようす', null, null, true),
  ('5', 'left', '左の', 'word', 'いろ・ようす', null, null, true),
  ('5', 'same', '同じ', 'word', 'いろ・ようす', null, null, true),
  ('5', 'different', 'ちがう', 'word', 'いろ・ようす', null, null, true),
  ('5', 'happy', '幸せな', 'word', 'きもち', null, null, true),
  ('5', 'sad', '悲しい', 'word', 'きもち', null, null, true),
  ('5', 'angry', 'おこった', 'word', 'きもち', null, null, true),
  ('5', 'tired', 'つかれた', 'word', 'きもち', null, null, true),
  ('5', 'hungry', 'おなかがすいた', 'word', 'きもち', null, null, true),
  ('5', 'sick', '病気の', 'word', 'きもち', null, null, true),
  ('5', 'glad', 'うれしい', 'word', 'きもち', null, null, true),
  ('5', 'sorry', 'すまなく思う', 'word', 'きもち', null, null, true),
  ('5', 'excited', 'わくわくした', 'word', 'きもち', null, null, true),
  ('5', 'afraid', 'こわがって', 'word', 'きもち', null, null, true),
  ('5', 'lonely', 'さびしい', 'word', 'きもち', null, null, true),
  ('5', 'love', '愛', 'word', 'きもち', null, null, true),
  ('5', 'dream', '夢', 'word', 'きもち', null, null, true),
  ('5', 'bag', 'かばん', 'word', 'もの', null, null, true),
  ('5', 'ball', 'ボール', 'word', 'もの', null, null, true),
  ('5', 'bed', 'ベッド', 'word', 'もの', null, null, true),
  ('5', 'bicycle', '自転車', 'word', 'もの', null, null, true),
  ('5', 'book', '本', 'word', 'もの', null, null, true),
  ('5', 'box', '箱', 'word', 'もの', null, null, true),
  ('5', 'camera', 'カメラ', 'word', 'もの', null, null, true),
  ('5', 'cap', '野球ぼう', 'word', 'もの', null, null, true),
  ('5', 'hat', 'ぼうし', 'word', 'もの', null, null, true),
  ('5', 'car', '車', 'word', 'もの', null, null, true),
  ('5', 'chair', 'いす', 'word', 'もの', null, null, true),
  ('5', 'clock', '（置き・かけ）時計', 'word', 'もの', null, null, true),
  ('5', 'computer', 'コンピューター', 'word', 'もの', null, null, true),
  ('5', 'desk', '机', 'word', 'もの', null, null, true),
  ('5', 'doll', '人形', 'word', 'もの', null, null, true),
  ('5', 'door', 'ドア', 'word', 'もの', null, null, true),
  ('5', 'glass', 'コップ、ガラス', 'word', 'もの', null, null, true),
  ('5', 'key', 'かぎ', 'word', 'もの', null, null, true),
  ('5', 'knife', 'ナイフ', 'word', 'もの', null, null, true),
  ('5', 'letter', '手紙', 'word', 'もの', null, null, true),
  ('5', 'map', '地図', 'word', 'もの', null, null, true),
  ('5', 'money', 'お金', 'word', 'もの', null, null, true),
  ('5', 'notebook', 'ノート', 'word', 'もの', null, null, true),
  ('5', 'paper', '紙', 'word', 'もの', null, null, true),
  ('5', 'pen', 'ペン', 'word', 'もの', null, null, true),
  ('5', 'pencil', 'えんぴつ', 'word', 'もの', null, null, true),
  ('5', 'phone', '電話', 'word', 'もの', null, null, true),
  ('5', 'piano', 'ピアノ', 'word', 'もの', null, null, true),
  ('5', 'guitar', 'ギター', 'word', 'もの', null, null, true),
  ('5', 'picture', '絵、写真', 'word', 'もの', null, null, true),
  ('5', 'radio', 'ラジオ', 'word', 'もの', null, null, true),
  ('5', 'shirt', 'シャツ', 'word', 'もの', null, null, true),
  ('5', 'shoe', 'くつ', 'word', 'もの', null, null, true),
  ('5', 'skirt', 'スカート', 'word', 'もの', null, null, true),
  ('5', 'jacket', '上着', 'word', 'もの', null, null, true),
  ('5', 'coat', 'コート', 'word', 'もの', null, null, true),
  ('5', 'dress', 'ドレス', 'word', 'もの', null, null, true),
  ('5', 'table', 'テーブル', 'word', 'もの', null, null, true),
  ('5', 'TV', 'テレビ', 'word', 'もの', null, null, true),
  ('5', 'toy', 'おもちゃ', 'word', 'もの', null, null, true),
  ('5', 'umbrella', 'かさ', 'word', 'もの', null, null, true),
  ('5', 'window', '窓', 'word', 'もの', null, null, true),
  ('5', 'bus', 'バス', 'word', 'もの', null, null, true),
  ('5', 'train', '電車', 'word', 'もの', null, null, true),
  ('5', 'plane', '飛行機', 'word', 'もの', null, null, true),
  ('5', 'boat', 'ボート', 'word', 'もの', null, null, true),
  ('5', 'ship', '船', 'word', 'もの', null, null, true),
  ('5', 'card', 'カード', 'word', 'もの', null, null, true),
  ('5', 'present', 'プレゼント', 'word', 'もの', null, null, true),
  ('5', 'towel', 'タオル', 'word', 'もの', null, null, true),
  ('5', 'bottle', 'びん', 'word', 'もの', null, null, true),
  ('5', 'ticket', '切符、チケット', 'word', 'もの', null, null, true),
  ('5', 'house', '家', 'word', 'ばしょ', null, null, true),
  ('5', 'home', '自分の家、家庭', 'word', 'ばしょ', null, null, true),
  ('5', 'park', '公園', 'word', 'ばしょ', null, null, true),
  ('5', 'zoo', '動物園', 'word', 'ばしょ', null, null, true),
  ('5', 'library', '図書館', 'word', 'ばしょ', null, null, true),
  ('5', 'station', '駅', 'word', 'ばしょ', null, null, true),
  ('5', 'hospital', '病院', 'word', 'ばしょ', null, null, true),
  ('5', 'restaurant', 'レストラン', 'word', 'ばしょ', null, null, true),
  ('5', 'shop', '店', 'word', 'ばしょ', null, null, true),
  ('5', 'supermarket', 'スーパーマーケット', 'word', 'ばしょ', null, null, true),
  ('5', 'bookstore', '本屋', 'word', 'ばしょ', null, null, true),
  ('5', 'city', '都市', 'word', 'ばしょ', null, null, true),
  ('5', 'town', '町', 'word', 'ばしょ', null, null, true),
  ('5', 'room', '部屋', 'word', 'ばしょ', null, null, true),
  ('5', 'kitchen', '台所', 'word', 'ばしょ', null, null, true),
  ('5', 'bathroom', 'ふろ場、トイレ', 'word', 'ばしょ', null, null, true),
  ('5', 'bedroom', '寝室', 'word', 'ばしょ', null, null, true),
  ('5', 'garden', '庭', 'word', 'ばしょ', null, null, true),
  ('5', 'beach', '浜辺', 'word', 'ばしょ', null, null, true),
  ('5', 'sea', '海', 'word', 'ばしょ', null, null, true),
  ('5', 'river', '川', 'word', 'ばしょ', null, null, true),
  ('5', 'mountain', '山', 'word', 'ばしょ', null, null, true),
  ('5', 'pool', 'プール', 'word', 'ばしょ', null, null, true),
  ('5', 'farm', '農場', 'word', 'ばしょ', null, null, true),
  ('5', 'street', '通り', 'word', 'ばしょ', null, null, true),
  ('5', 'bridge', '橋', 'word', 'ばしょ', null, null, true),
  ('5', 'hotel', 'ホテル', 'word', 'ばしょ', null, null, true),
  ('5', 'airport', '空港', 'word', 'ばしょ', null, null, true),
  ('5', 'temple', '寺', 'word', 'ばしょ', null, null, true),
  ('5', 'island', '島', 'word', 'ばしょ', null, null, true),
  ('5', 'world', '世界', 'word', 'ばしょ', null, null, true),
  ('5', 'school', '学校', 'word', 'がっこう', null, null, true),
  ('5', 'class', 'クラス、授業', 'word', 'がっこう', null, null, true),
  ('5', 'classroom', '教室', 'word', 'がっこう', null, null, true),
  ('5', 'lesson', 'レッスン、けいこ', 'word', 'がっこう', null, null, true),
  ('5', 'homework', '宿題', 'word', 'がっこう', null, null, true),
  ('5', 'test', 'テスト', 'word', 'がっこう', null, null, true),
  ('5', 'math', '算数、数学', 'word', 'がっこう', null, null, true),
  ('5', 'music', '音楽', 'word', 'がっこう', null, null, true),
  ('5', 'art', '図工、美術', 'word', 'がっこう', null, null, true),
  ('5', 'science', '理科', 'word', 'がっこう', null, null, true),
  ('5', 'history', '歴史', 'word', 'がっこう', null, null, true),
  ('5', 'subject', '教科', 'word', 'がっこう', null, null, true),
  ('5', 'dictionary', '辞書', 'word', 'がっこう', null, null, true),
  ('5', 'club', 'クラブ、部', 'word', 'がっこう', null, null, true),
  ('5', 'question', '質問', 'word', 'がっこう', null, null, true),
  ('5', 'answer', '答え', 'word', 'がっこう', null, null, true),
  ('5', 'word', '単語、ことば', 'word', 'がっこう', null, null, true),
  ('5', 'story', '物語', 'word', 'がっこう', null, null, true),
  ('5', 'song', '歌', 'word', 'がっこう', null, null, true),
  ('5', 'English', '英語', 'word', 'がっこう', null, null, true),
  ('5', 'baseball', '野球', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'basketball', 'バスケットボール', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'soccer', 'サッカー', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'tennis', 'テニス', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'volleyball', 'バレーボール', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'swimming', '水泳', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'sport', 'スポーツ', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'game', 'ゲーム、試合', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'team', 'チーム', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'party', 'パーティー', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'camp', 'キャンプ', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'picnic', 'ピクニック', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'movie', '映画', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'concert', 'コンサート', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'hobby', 'しゅみ', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'trip', '旅行', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'festival', 'お祭り', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'fun', '楽しみ', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'shopping', '買い物', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'fishing', '魚つり', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'kite', 'たこ（たこあげの）', 'word', 'あそび・スポーツ', null, null, true),
  ('5', 'sky', '空', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'sun', '太陽', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'moon', '月（空の）', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'star', '星', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'rain', '雨', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'snow', '雪', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'cloud', '雲', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'wind', '風', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'weather', '天気', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'tree', '木', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'flower', '花', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'leaf', '葉', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'sunny', '晴れた', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'rainy', '雨の', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'cloudy', 'くもりの', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'snowy', '雪の', 'word', 'しぜん・てんき', null, null, true),
  ('5', 'eat', '食べる', 'word', 'うごき', null, null, true),
  ('5', 'drink', '飲む', 'word', 'うごき', null, null, true),
  ('5', 'go', '行く', 'word', 'うごき', null, null, true),
  ('5', 'come', '来る', 'word', 'うごき', null, null, true),
  ('5', 'run', '走る', 'word', 'うごき', null, null, true),
  ('5', 'walk', '歩く', 'word', 'うごき', null, null, true),
  ('5', 'swim', '泳ぐ', 'word', 'うごき', null, null, true),
  ('5', 'play', '遊ぶ、（スポーツを）する', 'word', 'うごき', null, null, true),
  ('5', 'sing', '歌う', 'word', 'うごき', null, null, true),
  ('5', 'dance', 'おどる', 'word', 'うごき', null, null, true),
  ('5', 'read', '読む', 'word', 'うごき', null, null, true),
  ('5', 'write', '書く', 'word', 'うごき', null, null, true),
  ('5', 'speak', '話す', 'word', 'うごき', null, null, true),
  ('5', 'talk', 'しゃべる', 'word', 'うごき', null, null, true),
  ('5', 'say', '言う', 'word', 'うごき', null, null, true),
  ('5', 'tell', '伝える', 'word', 'うごき', null, null, true),
  ('5', 'listen', '（注意して）聞く', 'word', 'うごき', null, null, true),
  ('5', 'hear', '聞こえる', 'word', 'うごき', null, null, true),
  ('5', 'see', '見える', 'word', 'うごき', null, null, true),
  ('5', 'look', '見る', 'word', 'うごき', null, null, true),
  ('5', 'watch', '（じっと）見る', 'word', 'うごき', null, null, true),
  ('5', 'study', '勉強する', 'word', 'うごき', null, null, true),
  ('5', 'learn', '学ぶ', 'word', 'うごき', null, null, true),
  ('5', 'teach', '教える', 'word', 'うごき', null, null, true),
  ('5', 'cook', '料理する', 'word', 'うごき', null, null, true),
  ('5', 'make', '作る', 'word', 'うごき', null, null, true),
  ('5', 'help', '手伝う、助ける', 'word', 'うごき', null, null, true),
  ('5', 'like', '好きだ', 'word', 'うごき', null, null, true),
  ('5', 'want', 'ほしい', 'word', 'うごき', null, null, true),
  ('5', 'have', '持っている', 'word', 'うごき', null, null, true),
  ('5', 'get', '手に入れる', 'word', 'うごき', null, null, true),
  ('5', 'give', 'あたえる', 'word', 'うごき', null, null, true),
  ('5', 'take', '取る、持っていく', 'word', 'うごき', null, null, true),
  ('5', 'buy', '買う', 'word', 'うごき', null, null, true),
  ('5', 'sell', '売る', 'word', 'うごき', null, null, true),
  ('5', 'open', '開ける', 'word', 'うごき', null, null, true),
  ('5', 'close', '閉める', 'word', 'うごき', null, null, true),
  ('5', 'sit', 'すわる', 'word', 'うごき', null, null, true),
  ('5', 'stand', '立つ', 'word', 'うごき', null, null, true),
  ('5', 'sleep', 'ねむる', 'word', 'うごき', null, null, true),
  ('5', 'wash', '洗う', 'word', 'うごき', null, null, true),
  ('5', 'live', '住む', 'word', 'うごき', null, null, true),
  ('5', 'know', '知っている', 'word', 'うごき', null, null, true),
  ('5', 'think', '思う、考える', 'word', 'うごき', null, null, true),
  ('5', 'use', '使う', 'word', 'うごき', null, null, true),
  ('5', 'ride', '乗る', 'word', 'うごき', null, null, true),
  ('5', 'jump', 'とぶ、はねる', 'word', 'うごき', null, null, true),
  ('5', 'fly', '（空を）飛ぶ', 'word', 'うごき', null, null, true),
  ('5', 'stop', '止まる、止める', 'word', 'うごき', null, null, true),
  ('5', 'start', '始める', 'word', 'うごき', null, null, true),
  ('5', 'finish', '終える', 'word', 'うごき', null, null, true),
  ('5', 'visit', '訪ねる', 'word', 'うごき', null, null, true),
  ('5', 'wait', '待つ', 'word', 'うごき', null, null, true),
  ('5', 'work', '働く', 'word', 'うごき', null, null, true),
  ('5', 'draw', '（線で）絵をかく', 'word', 'うごき', null, null, true),
  ('5', 'paint', '（絵の具で）絵をかく', 'word', 'うごき', null, null, true),
  ('5', 'enjoy', '楽しむ', 'word', 'うごき', null, null, true),
  ('5', 'practice', '練習する', 'word', 'うごき', null, null, true),
  ('5', 'wear', '着ている', 'word', 'うごき', null, null, true),
  ('5', 'carry', '運ぶ', 'word', 'うごき', null, null, true),
  ('5', 'catch', 'つかまえる', 'word', 'うごき', null, null, true),
  ('5', 'kick', 'ける', 'word', 'うごき', null, null, true),
  ('5', 'meet', '会う', 'word', 'うごき', null, null, true),
  ('5', 'call', '電話する、呼ぶ', 'word', 'うごき', null, null, true),
  ('5', 'need', '必要とする', 'word', 'うごき', null, null, true),
  ('5', 'find', '見つける', 'word', 'うごき', null, null, true),
  ('5', 'put', '置く', 'word', 'うごき', null, null, true),
  ('5', 'ask', 'たずねる', 'word', 'うごき', null, null, true),
  ('5', 'yes', 'はい', 'word', 'ことば', null, null, true),
  ('5', 'no', 'いいえ', 'word', 'ことば', null, null, true),
  ('5', 'here', 'ここ', 'word', 'ことば', null, null, true),
  ('5', 'there', 'そこ', 'word', 'ことば', null, null, true),
  ('5', 'very', 'とても', 'word', 'ことば', null, null, true),
  ('5', 'too', '〜も（また）', 'word', 'ことば', null, null, true),
  ('5', 'often', 'よく、しばしば', 'word', 'ことば', null, null, true),
  ('5', 'always', 'いつも', 'word', 'ことば', null, null, true),
  ('5', 'usually', 'ふつうは', 'word', 'ことば', null, null, true),
  ('5', 'together', 'いっしょに', 'word', 'ことば', null, null, true),
  ('5', 'again', 'もう一度', 'word', 'ことば', null, null, true),
  ('5', 'please', 'どうぞ、おねがいします', 'word', 'ことば', null, null, true),
  ('5', 'where', 'どこ', 'word', 'ことば', null, null, true),
  ('5', 'when', 'いつ', 'word', 'ことば', null, null, true),
  ('5', 'what', '何', 'word', 'ことば', null, null, true),
  ('5', 'who', 'だれ', 'word', 'ことば', null, null, true),
  ('5', 'why', 'なぜ', 'word', 'ことば', null, null, true),
  ('5', 'how', 'どうやって', 'word', 'ことば', null, null, true),
  ('5', 'which', 'どちら', 'word', 'ことば', null, null, true),
  ('5', 'in', '〜の中に', 'word', 'ことば', null, null, true),
  ('5', 'on', '〜の上に', 'word', 'ことば', null, null, true),
  ('5', 'under', '〜の下に', 'word', 'ことば', null, null, true),
  ('5', 'near', '〜の近くに', 'word', 'ことば', null, null, true),
  ('5', 'with', '〜といっしょに', 'word', 'ことば', null, null, true),
  ('5', 'from', '〜から', 'word', 'ことば', null, null, true),
  ('5', 'and', 'そして、〜と', 'word', 'ことば', null, null, true),
  ('5', 'but', 'しかし', 'word', 'ことば', null, null, true),
  ('5', 'or', 'または', 'word', 'ことば', null, null, true),
  ('5', 'because', 'なぜなら', 'word', 'ことば', null, null, true),
  ('5', 'hello', 'こんにちは', 'word', 'かいわ', null, null, true),
  ('5', 'hi', 'やあ', 'word', 'かいわ', null, null, true),
  ('5', 'bye', 'さようなら', 'word', 'かいわ', null, null, true),
  ('5', 'good morning', 'おはよう', 'word', 'かいわ', null, null, true),
  ('5', 'good afternoon', 'こんにちは（午後のあいさつ）', 'word', 'かいわ', null, null, true),
  ('5', 'good night', 'おやすみなさい', 'word', 'かいわ', null, null, true),
  ('5', 'thanks', 'ありがとう', 'word', 'かいわ', null, null, true),
  ('5', 'welcome', 'ようこそ', 'word', 'かいわ', null, null, true),
  ('5', 'OK', 'いいよ、わかった', 'word', 'かいわ', null, null, true),
  ('5', 'get up', '起きる', 'phrase', 'うごき', 'I [[get up]] at six every day.', '私は毎日6時に[[起きる]]。', true),
  ('5', 'go to bed', 'ねる（ベッドに入る）', 'phrase', 'うごき', 'I [[go to bed]] at nine.', '私は9時に[[ねる]]。', true),
  ('5', 'wake up', '目がさめる', 'phrase', 'うごき', 'I [[wake up]] early on Sundays.', '日曜日は早く[[目がさめる]]。', true),
  ('5', 'look at', '〜を見る', 'phrase', 'うごき', '[[Look at]] this picture.', 'この絵を[[見て]]。', true),
  ('5', 'listen to', '〜を聞く', 'phrase', 'うごき', 'I [[listen to]] music every night.', '私は毎晩、音楽を[[聞く]]。', true),
  ('5', 'sit down', 'すわる、席につく', 'phrase', 'うごき', 'Please [[sit down]].', '[[すわって]]ください。', true),
  ('5', 'stand up', '立つ、立ち上がる', 'phrase', 'うごき', 'Please [[stand up]].', '[[立って]]ください。', true),
  ('5', 'come in', '（中に）入る', 'phrase', 'うごき', 'Please [[come in]].', 'どうぞ[[入って]]ください。', true),
  ('5', 'go home', '家に帰る', 'phrase', 'うごき', 'Let''s [[go home]] now.', 'もう[[家に帰]]ろう。', true),
  ('5', 'come home', '帰宅する', 'phrase', 'うごき', 'My father [[comes home]] at seven.', '父は7時に[[帰宅する]]。', true),
  ('5', 'at home', '家で', 'phrase', 'ばしょ', 'I study [[at home]].', '私は[[家で]]勉強する。', true),
  ('5', 'at school', '学校で', 'phrase', 'がっこう', 'We play soccer [[at school]].', '私たちは[[学校で]]サッカーをする。', true),
  ('5', 'every day', '毎日', 'phrase', 'じかん', 'I read books [[every day]].', '私は[[毎日]]本を読む。', true),
  ('5', 'a lot of', 'たくさんの', 'phrase', 'かず', 'I have [[a lot of]] books.', '私は[[たくさんの]]本を持っている。', true),
  ('5', 'play the piano', 'ピアノをひく', 'phrase', 'あそび・スポーツ', 'She can [[play the piano]] well.', '彼女は上手に[[ピアノをひく]]ことができる。', true),
  ('5', 'take a picture', '写真をとる', 'phrase', 'あそび・スポーツ', 'Let''s [[take a picture]] here.', 'ここで[[写真をとろう]]。', true),
  ('5', 'go shopping', '買い物に行く', 'phrase', 'あそび・スポーツ', 'We [[go shopping]] on Saturdays.', '私たちは土曜日に[[買い物に行く]]。', true),
  ('5', 'go to school', '学校へ行く', 'phrase', 'がっこう', 'I [[go to school]] by bus.', '私はバスで[[学校へ行く]]。', true),
  ('5', 'watch TV', 'テレビを見る', 'phrase', 'あそび・スポーツ', 'I [[watch TV]] after dinner.', '私は夕ごはんのあとに[[テレビを見る]]。', true),
  ('5', 'do my homework', '宿題をする', 'phrase', 'がっこう', 'I [[do my homework]] after school.', '私は放課後に[[宿題をする]]。', true),
  ('5', 'after school', '放課後', 'phrase', 'じかん', 'Let''s play tennis [[after school]].', '[[放課後]]にテニスをしよう。', true),
  ('5', 'in the morning', '朝に、午前中に', 'phrase', 'じかん', 'I run in the park [[in the morning]].', '私は[[朝に]]公園で走る。', true),
  ('5', 'how many', 'いくつの', 'phrase', 'かず', '[[How many]] cats do you have?', 'ねこを[[何びき]]飼っていますか。', true),
  ('5', 'how much', 'いくら', 'phrase', 'かず', '[[How much]] is this pen?', 'このペンは[[いくら]]ですか。', true),
  ('5', 'what time', '何時', 'phrase', 'じかん', '[[What time]] is it now?', '今[[何時]]ですか。', true),
  ('5', 'How are you?', '元気ですか。', 'idiom', 'かいわ', '"[[How are you?]]" "I''m fine, thank you."', '「[[元気ですか。]]」「元気です、ありがとう。」', true),
  ('5', 'Nice to meet you.', 'はじめまして。', 'idiom', 'かいわ', '"Hi, I''m Ken. [[Nice to meet you.]]"', '「やあ、ぼくはケン。[[はじめまして。]]」', true),
  ('5', 'See you.', 'またね。', 'idiom', 'かいわ', '"Bye, Emi." "[[See you.]]"', '「さようなら、エミ。」「[[またね。]]」', true),
  ('5', 'Thank you very much.', 'どうもありがとう。', 'idiom', 'かいわ', '"Here''s your bag." "[[Thank you very much.]]"', '「はい、きみのかばん。」「[[どうもありがとう。]]」', true),
  ('5', 'You''re welcome.', 'どういたしまして。', 'idiom', 'かいわ', '"Thank you." "[[You''re welcome.]]"', '「ありがとう。」「[[どういたしまして。]]」', true),
  ('5', 'Excuse me.', 'すみません。', 'idiom', 'かいわ', '"[[Excuse me.]] Where is the station?"', '「[[すみません。]]駅はどこですか。」', true),
  ('5', 'I''m sorry.', 'ごめんなさい。', 'idiom', 'かいわ', '"[[I''m sorry.]] I''m late."', '「[[ごめんなさい。]]おくれました。」', true),
  ('5', 'Here you are.', 'はい、どうぞ。', 'idiom', 'かいわ', '"Can I have the salt?" "[[Here you are.]]"', '「塩を取ってくれる？」「[[はい、どうぞ。]]」', true),
  ('5', 'How about you?', 'あなたはどう？', 'idiom', 'かいわ', '"I like dogs. [[How about you?]]"', '「私は犬が好き。[[あなたはどう？]]」', true),
  ('5', 'Me too.', '私も。', 'idiom', 'かいわ', '"I like pizza." "[[Me too.]]"', '「ピザが好き。」「[[私も。]]」', true),
  ('5', 'Of course.', 'もちろん。', 'idiom', 'かいわ', '"Can you help me?" "[[Of course.]]"', '「手伝ってくれる？」「[[もちろん。]]」', true),
  ('5', 'That''s right.', 'そのとおり。', 'idiom', 'かいわ', '"Is this your pen?" "Yes, [[that''s right.]]"', '「これはきみのペン？」「うん、[[そのとおり。]]」', true),
  ('5', 'Let''s go.', '行こう。', 'idiom', 'かいわ', '"The bus is here. [[Let''s go.]]"', '「バスが来たよ。[[行こう。]]」', true),
  ('5', 'Good job.', 'よくできました。', 'idiom', 'かいわ', '"I got 100 on the test!" "[[Good job.]]"', '「テストで100点とったよ！」「[[よくできました。]]」', true),
  ('5', 'Happy birthday!', 'お誕生日おめでとう！', 'idiom', 'かいわ', '"[[Happy birthday!]] This is for you."', '「[[お誕生日おめでとう！]]これはきみに。」', true),
  ('5', 'Just a minute.', 'ちょっと待って。', 'idiom', 'かいわ', '"Are you ready?" "[[Just a minute.]]"', '「準備できた？」「[[ちょっと待って。]]」', true),
  ('5', 'I see.', 'なるほど。', 'idiom', 'かいわ', '"This is how to use it." "[[I see.]]"', '「こうやって使うんだよ。」「[[なるほど。]]」', true),
  ('5', 'Sounds good.', 'いいね。', 'idiom', 'かいわ', '"Let''s play soccer." "[[Sounds good.]]"', '「サッカーしよう。」「[[いいね。]]」', true),
  ('5', 'What''s this?', 'これは何？', 'idiom', 'かいわ', '"[[What''s this?]]" "It''s a map."', '「[[これは何？]]」「地図だよ。」', true),
  ('5', 'Good luck.', 'がんばってね。', 'idiom', 'かいわ', '"I have a test today." "[[Good luck.]]"', '「今日テストがあるんだ。」「[[がんばってね。]]」', true)
on conflict (level, en) do update set
  ja = excluded.ja, type = excluded.type, theme = excluded.theme,
  example_en = excluded.example_en, example_ja = excluded.example_ja, active = true;
commit;
