-- 4級の語彙（580語）。scripts/vocab/build-seed.mjs で vocab_4.tsv から生成。手で編集しない。
-- 単語の選定は CEFR-J Wordlist Version 1.6（東京外国語大学投野由紀夫研究室）を元にしている。
-- Supabase の SQL Editor で実行する。同じ (level, en) があれば内容を上書きし、id は変えない（記録を壊さない）。
begin;
insert into public.vocab_items (level, en, ja, type, theme, example_en, example_ja, active) values
  ('4', 'beef', '牛肉', 'word', 'たべもの', null, null, true),
  ('4', 'biscuit', 'ビスケット', 'word', 'たべもの', null, null, true),
  ('4', 'bean', '豆', 'word', 'たべもの', null, null, true),
  ('4', 'bowl', 'おわん、どんぶり', 'word', 'たべもの', null, null, true),
  ('4', 'cream', 'クリーム', 'word', 'たべもの', null, null, true),
  ('4', 'meal', '食事', 'word', 'たべもの', null, null, true),
  ('4', 'curry', 'カレー', 'word', 'たべもの', null, null, true),
  ('4', 'carrot', 'にんじん', 'word', 'たべもの', null, null, true),
  ('4', 'onion', 'たまねぎ', 'word', 'たべもの', null, null, true),
  ('4', 'lemon', 'レモン', 'word', 'たべもの', null, null, true),
  ('4', 'melon', 'メロン', 'word', 'たべもの', null, null, true),
  ('4', 'pear', '洋なし', 'word', 'たべもの', null, null, true),
  ('4', 'mushroom', 'きのこ', 'word', 'たべもの', null, null, true),
  ('4', 'salt', '塩', 'word', 'たべもの', null, null, true),
  ('4', 'pepper', 'こしょう', 'word', 'たべもの', null, null, true),
  ('4', 'sausage', 'ソーセージ', 'word', 'たべもの', null, null, true),
  ('4', 'steak', 'ステーキ', 'word', 'たべもの', null, null, true),
  ('4', 'spaghetti', 'スパゲッティ', 'word', 'たべもの', null, null, true),
  ('4', 'dessert', 'デザート', 'word', 'たべもの', null, null, true),
  ('4', 'snack', 'おやつ、軽食', 'word', 'たべもの', null, null, true),
  ('4', 'honey', 'はちみつ', 'word', 'たべもの', null, null, true),
  ('4', 'jam', 'ジャム', 'word', 'たべもの', null, null, true),
  ('4', 'ham', 'ハム', 'word', 'たべもの', null, null, true),
  ('4', 'fork', 'フォーク', 'word', 'たべもの', null, null, true),
  ('4', 'spoon', 'スプーン', 'word', 'たべもの', null, null, true),
  ('4', 'plate', '取り皿', 'word', 'たべもの', null, null, true),
  ('4', 'toast', 'トースト', 'word', 'たべもの', null, null, true),
  ('4', 'menu', 'メニュー', 'word', 'たべもの', null, null, true),
  ('4', 'seafood', '魚介類', 'word', 'たべもの', null, null, true),
  ('4', 'duck', 'アヒル', 'word', 'どうぶつ', null, null, true),
  ('4', 'elephant', 'ゾウ', 'word', 'どうぶつ', null, null, true),
  ('4', 'insect', 'こん虫', 'word', 'どうぶつ', null, null, true),
  ('4', 'dinosaur', '恐竜', 'word', 'どうぶつ', null, null, true),
  ('4', 'grandparent', '祖父母', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'parent', '親', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'husband', '夫', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'wife', '妻', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'person', '人', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'guest', '招待客', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'neighbor', '近所の人', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'king', '王', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'queen', '女王', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'prince', '王子', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'princess', '王女', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'actor', '俳優', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'musician', '音楽家', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'writer', '作家', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'scientist', '科学者', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'engineer', '技術者', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'reporter', '記者', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'police officer', '警察官', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'waiter', 'ウエーター', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'worker', '働く人', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'leader', 'リーダー', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'coach', 'コーチ', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'owner', '持ち主', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'visitor', '訪問者', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'tourist', '観光客', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'pilot', 'パイロット', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'dentist', '歯医者', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'teenager', '10代の若者', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'adult', 'おとな', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'member', 'メンバー、一員', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'fan', 'ファン', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'hero', 'ヒーロー、英雄', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'partner', '相手、パートナー', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'dancer', 'ダンサー', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'painter', '画家', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'customer', '（店の）客', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'passenger', '乗客', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'stranger', '知らない人', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'captain', 'キャプテン、船長', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'Mr.', '〜さん（男性）', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'Ms.', '〜さん（女性）', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'kid', '子ども（くだけた言い方）', 'word', 'かぞく・ひと', null, null, true),
  ('4', 'heart', '心臓、心', 'word', 'からだ', null, null, true),
  ('4', 'brain', '脳', 'word', 'からだ', null, null, true),
  ('4', 'bone', '骨', 'word', 'からだ', null, null, true),
  ('4', 'headache', '頭痛', 'word', 'からだ', null, null, true),
  ('4', 'fever', '熱（病気の）', 'word', 'からだ', null, null, true),
  ('4', 'health', '健康', 'word', 'からだ', null, null, true),
  ('4', 'medicine', '薬', 'word', 'からだ', null, null, true),
  ('4', 'stomach', 'おなか、胃', 'word', 'からだ', null, null, true),
  ('4', 'stomachache', '腹痛', 'word', 'からだ', null, null, true),
  ('4', 'toothache', '歯の痛み', 'word', 'からだ', null, null, true),
  ('4', 'toe', '足の指', 'word', 'からだ', null, null, true),
  ('4', 'lip', 'くちびる', 'word', 'からだ', null, null, true),
  ('4', 'cheek', 'ほお', 'word', 'からだ', null, null, true),
  ('4', 'voice', '声', 'word', 'からだ', null, null, true),
  ('4', 'blood', '血', 'word', 'からだ', null, null, true),
  ('4', 'grade', '学年、成績', 'word', 'がっこう', null, null, true),
  ('4', 'grammar', '文法', 'word', 'がっこう', null, null, true),
  ('4', 'language', '言語', 'word', 'がっこう', null, null, true),
  ('4', 'sentence', '文', 'word', 'がっこう', null, null, true),
  ('4', 'page', 'ページ', 'word', 'がっこう', null, null, true),
  ('4', 'ruler', '定規', 'word', 'がっこう', null, null, true),
  ('4', 'list', '一覧表、リスト', 'word', 'がっこう', null, null, true),
  ('4', 'note', 'メモ', 'word', 'がっこう', null, null, true),
  ('4', 'example', '例', 'word', 'がっこう', null, null, true),
  ('4', 'problem', '問題', 'word', 'がっこう', null, null, true),
  ('4', 'reason', '理由', 'word', 'がっこう', null, null, true),
  ('4', 'idea', '考え、アイデア', 'word', 'がっこう', null, null, true),
  ('4', 'information', '情報', 'word', 'がっこう', null, null, true),
  ('4', 'rule', '規則', 'word', 'がっこう', null, null, true),
  ('4', 'speech', 'スピーチ', 'word', 'がっこう', null, null, true),
  ('4', 'poem', '詩', 'word', 'がっこう', null, null, true),
  ('4', 'magazine', '雑誌', 'word', 'がっこう', null, null, true),
  ('4', 'newspaper', '新聞', 'word', 'がっこう', null, null, true),
  ('4', 'news', 'ニュース', 'word', 'がっこう', null, null, true),
  ('4', 'message', '伝言、メッセージ', 'word', 'がっこう', null, null, true),
  ('4', 'email', 'Eメール', 'word', 'がっこう', null, null, true),
  ('4', 'textbook', '教科書', 'word', 'がっこう', null, null, true),
  ('4', 'exam', '試験', 'word', 'がっこう', null, null, true),
  ('4', 'uniform', '制服', 'word', 'がっこう', null, null, true),
  ('4', 'university', '大学', 'word', 'がっこう', null, null, true),
  ('4', 'high school', '高校', 'word', 'がっこう', null, null, true),
  ('4', 'playground', '運動場', 'word', 'がっこう', null, null, true),
  ('4', 'blackboard', '黒板', 'word', 'がっこう', null, null, true),
  ('4', 'calendar', 'カレンダー', 'word', 'がっこう', null, null, true),
  ('4', 'diary', '日記', 'word', 'がっこう', null, null, true),
  ('4', 'vocabulary', '語い', 'word', 'がっこう', null, null, true),
  ('4', 'mistake', 'まちがい', 'word', 'がっこう', null, null, true),
  ('4', 'quiz', 'クイズ', 'word', 'がっこう', null, null, true),
  ('4', 'report', '報告、レポート', 'word', 'がっこう', null, null, true),
  ('4', 'contest', 'コンテスト', 'word', 'がっこう', null, null, true),
  ('4', 'building', '建物', 'word', 'ばしょ', null, null, true),
  ('4', 'church', '教会', 'word', 'ばしょ', null, null, true),
  ('4', 'cinema', '映画館', 'word', 'ばしょ', null, null, true),
  ('4', 'theater', '劇場', 'word', 'ばしょ', null, null, true),
  ('4', 'office', '事務所、会社', 'word', 'ばしょ', null, null, true),
  ('4', 'factory', '工場', 'word', 'ばしょ', null, null, true),
  ('4', 'palace', '宮殿', 'word', 'ばしょ', null, null, true),
  ('4', 'tower', '塔', 'word', 'ばしょ', null, null, true),
  ('4', 'hall', 'ホール、会館', 'word', 'ばしょ', null, null, true),
  ('4', 'hill', '丘', 'word', 'ばしょ', null, null, true),
  ('4', 'field', '野原、畑', 'word', 'ばしょ', null, null, true),
  ('4', 'ground', '地面', 'word', 'ばしょ', null, null, true),
  ('4', 'yard', '（家の）裏庭', 'word', 'ばしょ', null, null, true),
  ('4', 'corner', '角', 'word', 'ばしょ', null, null, true),
  ('4', 'floor', '床、（建物の）階', 'word', 'ばしょ', null, null, true),
  ('4', 'wall', 'かべ', 'word', 'ばしょ', null, null, true),
  ('4', 'living room', '居間', 'word', 'ばしょ', null, null, true),
  ('4', 'dining room', '食堂', 'word', 'ばしょ', null, null, true),
  ('4', 'place', '場所', 'word', 'ばしょ', null, null, true),
  ('4', 'hometown', '故郷', 'word', 'ばしょ', null, null, true),
  ('4', 'museum', '博物館、美術館', 'word', 'ばしょ', null, null, true),
  ('4', 'castle', '城', 'word', 'ばしょ', null, null, true),
  ('4', 'village', '村', 'word', 'ばしょ', null, null, true),
  ('4', 'lake', '湖', 'word', 'ばしょ', null, null, true),
  ('4', 'forest', '森', 'word', 'ばしょ', null, null, true),
  ('4', 'country', '国', 'word', 'ばしょ', null, null, true),
  ('4', 'countryside', 'いなか', 'word', 'ばしょ', null, null, true),
  ('4', 'apartment', 'アパート、マンション', 'word', 'ばしょ', null, null, true),
  ('4', 'market', '市場', 'word', 'ばしょ', null, null, true),
  ('4', 'post office', '郵便局', 'word', 'ばしょ', null, null, true),
  ('4', 'police station', '警察署', 'word', 'ばしょ', null, null, true),
  ('4', 'department store', 'デパート', 'word', 'ばしょ', null, null, true),
  ('4', 'bus stop', 'バス停', 'word', 'ばしょ', null, null, true),
  ('4', 'road', '道路', 'word', 'ばしょ', null, null, true),
  ('4', 'stadium', 'スタジアム', 'word', 'ばしょ', null, null, true),
  ('4', 'earth', '地球', 'word', 'ばしょ', null, null, true),
  ('4', 'space', '宇宙', 'word', 'ばしょ', null, null, true),
  ('4', 'east', '東', 'word', 'ばしょ', null, null, true),
  ('4', 'west', '西', 'word', 'ばしょ', null, null, true),
  ('4', 'north', '北', 'word', 'ばしょ', null, null, true),
  ('4', 'south', '南', 'word', 'ばしょ', null, null, true),
  ('4', 'abroad', '外国へ、外国で', 'word', 'ばしょ', null, null, true),
  ('4', 'album', 'アルバム', 'word', 'もの', null, null, true),
  ('4', 'bell', 'ベル、かね', 'word', 'もの', null, null, true),
  ('4', 'brush', 'ブラシ、筆', 'word', 'もの', null, null, true),
  ('4', 'bucket', 'バケツ', 'word', 'もの', null, null, true),
  ('4', 'button', 'ボタン', 'word', 'もの', null, null, true),
  ('4', 'clothes', '服', 'word', 'もの', null, null, true),
  ('4', 'cloth', '布', 'word', 'もの', null, null, true),
  ('4', 'sofa', 'ソファー', 'word', 'もの', null, null, true),
  ('4', 'drum', 'たいこ、ドラム', 'word', 'もの', null, null, true),
  ('4', 'flag', '旗', 'word', 'もの', null, null, true),
  ('4', 'glasses', 'めがね', 'word', 'もの', null, null, true),
  ('4', 'gift', 'おくり物', 'word', 'もの', null, null, true),
  ('4', 'jeans', 'ジーンズ', 'word', 'もの', null, null, true),
  ('4', 'jewelry', '宝石類', 'word', 'もの', null, null, true),
  ('4', 'machine', '機械', 'word', 'もの', null, null, true),
  ('4', 'mail', '郵便', 'word', 'もの', null, null, true),
  ('4', 'photo', '写真', 'word', 'もの', null, null, true),
  ('4', 'pocket', 'ポケット', 'word', 'もの', null, null, true),
  ('4', 'poster', 'ポスター', 'word', 'もの', null, null, true),
  ('4', 'shelf', 'たな', 'word', 'もの', null, null, true),
  ('4', 'stone', '石', 'word', 'もの', null, null, true),
  ('4', 'tool', '道具', 'word', 'もの', null, null, true),
  ('4', 'truck', 'トラック', 'word', 'もの', null, null, true),
  ('4', 'taxi', 'タクシー', 'word', 'もの', null, null, true),
  ('4', 'subway', '地下鉄', 'word', 'もの', null, null, true),
  ('4', 'T-shirt', 'Tシャツ', 'word', 'もの', null, null, true),
  ('4', 'pants', 'ズボン', 'word', 'もの', null, null, true),
  ('4', 'vase', '花びん', 'word', 'もの', null, null, true),
  ('4', 'video', 'ビデオ、動画', 'word', 'もの', null, null, true),
  ('4', 'wheel', '車輪', 'word', 'もの', null, null, true),
  ('4', 'mirror', '鏡', 'word', 'もの', null, null, true),
  ('4', 'lamp', '電気スタンド、ランプ', 'word', 'もの', null, null, true),
  ('4', 'refrigerator', '冷蔵庫', 'word', 'もの', null, null, true),
  ('4', 'blanket', '毛布', 'word', 'もの', null, null, true),
  ('4', 'sock', 'くつ下', 'word', 'もの', null, null, true),
  ('4', 'scarf', 'マフラー、スカーフ', 'word', 'もの', null, null, true),
  ('4', 'glove', '手ぶくろ', 'word', 'もの', null, null, true),
  ('4', 'sweater', 'セーター', 'word', 'もの', null, null, true),
  ('4', 'raincoat', 'レインコート', 'word', 'もの', null, null, true),
  ('4', 'wallet', 'さいふ', 'word', 'もの', null, null, true),
  ('4', 'coin', '硬貨', 'word', 'もの', null, null, true),
  ('4', 'stamp', '切手', 'word', 'もの', null, null, true),
  ('4', 'printer', 'プリンター', 'word', 'もの', null, null, true),
  ('4', 'battery', '電池', 'word', 'もの', null, null, true),
  ('4', 'violin', 'バイオリン', 'word', 'もの', null, null, true),
  ('4', 'instrument', '楽器', 'word', 'もの', null, null, true),
  ('4', 'toothbrush', '歯ブラシ', 'word', 'もの', null, null, true),
  ('4', 'soap', 'せっけん', 'word', 'もの', null, null, true),
  ('4', 'scissors', 'はさみ', 'word', 'もの', null, null, true),
  ('4', 'suitcase', 'スーツケース', 'word', 'もの', null, null, true),
  ('4', 'ring', '指輪', 'word', 'もの', null, null, true),
  ('4', 'band', 'バンド', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'cartoon', '（テレビの）アニメ、まんが', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'drama', 'ドラマ、劇', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'football', 'フットボール', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'match', '（スポーツの）試合', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'goal', 'ゴール、目標', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'event', '行事、出来事', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'Olympics', 'オリンピック', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'vacation', '休暇', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'golf', 'ゴルフ', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'badminton', 'バドミントン', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'table tennis', '卓球', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'hiking', 'ハイキング', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'skiing', 'スキー', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'skating', 'スケート', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'video game', 'テレビゲーム', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'comic', 'まんが本', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'magic', '手品、魔法', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'chess', 'チェス', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'bat', 'バット', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'racket', 'ラケット', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'sightseeing', '観光', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'tour', 'ツアー、見学', 'word', 'あそび・スポーツ', null, null, true),
  ('4', 'ice', '氷', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'fire', '火、火事', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'grass', '草、しばふ', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'rose', 'バラ', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'sunshine', '日光', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'fog', 'きり', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'storm', 'あらし', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'wave', '波', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'plant', '植物', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'seed', '種', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'sunflower', 'ひまわり', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'nature', '自然', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'air', '空気', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'foggy', 'きりの深い', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'windy', '風の強い', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'temperature', '温度、気温', 'word', 'しぜん・てんき', null, null, true),
  ('4', 'tonight', '今夜', 'word', 'じかん', null, null, true),
  ('4', 'a.m.', '午前（時刻のあとにつける）', 'word', 'じかん', null, null, true),
  ('4', 'p.m.', '午後（時刻のあとにつける）', 'word', 'じかん', null, null, true),
  ('4', 'date', '日付', 'word', 'じかん', null, null, true),
  ('4', 'future', '未来、将来', 'word', 'じかん', null, null, true),
  ('4', 'moment', 'ちょっとの間', 'word', 'じかん', null, null, true),
  ('4', 'quarter', '4分の1、15分', 'word', 'じかん', null, null, true),
  ('4', 'end', '終わり', 'word', 'じかん', null, null, true),
  ('4', 'ago', '〜前に', 'word', 'じかん', null, null, true),
  ('4', 'soon', 'すぐに', 'word', 'じかん', null, null, true),
  ('4', 'early', '早く', 'word', 'じかん', null, null, true),
  ('4', 'late', 'おそく、おくれて', 'word', 'じかん', null, null, true),
  ('4', 'later', 'あとで', 'word', 'じかん', null, null, true),
  ('4', 'before', '〜の前に', 'word', 'じかん', null, null, true),
  ('4', 'after', '〜のあとに', 'word', 'じかん', null, null, true),
  ('4', 'until', '〜まで（ずっと）', 'word', 'じかん', null, null, true),
  ('4', 'noon', '正午', 'word', 'じかん', null, null, true),
  ('4', 'midnight', '真夜中', 'word', 'じかん', null, null, true),
  ('4', 'century', '世紀', 'word', 'じかん', null, null, true),
  ('4', 'weekday', '平日', 'word', 'じかん', null, null, true),
  ('4', 'schedule', '予定', 'word', 'じかん', null, null, true),
  ('4', 'number', '数、番号', 'word', 'かず', null, null, true),
  ('4', 'dollar', 'ドル', 'word', 'かず', null, null, true),
  ('4', 'price', '値段', 'word', 'かず', null, null, true),
  ('4', 'size', '大きさ、サイズ', 'word', 'かず', null, null, true),
  ('4', 'half', '半分', 'word', 'かず', null, null, true),
  ('4', 'hundred', '100', 'word', 'かず', null, null, true),
  ('4', 'thousand', '1000', 'word', 'かず', null, null, true),
  ('4', 'zero', '0', 'word', 'かず', null, null, true),
  ('4', 'first', '1番目の、最初の', 'word', 'かず', null, null, true),
  ('4', 'second', '2番目の', 'word', 'かず', null, null, true),
  ('4', 'third', '3番目の', 'word', 'かず', null, null, true),
  ('4', 'gold', '金の、金色の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'silver', '銀の、銀色の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'large', '（広さ・量が）大きい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'little', '少しの、小さい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'thick', '厚い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'thin', 'うすい、やせた', 'word', 'いろ・ようす', null, null, true),
  ('4', 'fat', '太った', 'word', 'いろ・ようす', null, null, true),
  ('4', 'full', 'いっぱいの', 'word', 'いろ・ようす', null, null, true),
  ('4', 'dry', 'かわいた', 'word', 'いろ・ようす', null, null, true),
  ('4', 'light', '軽い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'expensive', '値段が高い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'cheap', '安い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'important', '大切な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'special', '特別な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'strange', '奇妙な、ふしぎな', 'word', 'いろ・ようす', null, null, true),
  ('4', 'terrible', 'ひどい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'excellent', 'とても優れた', 'word', 'いろ・ようす', null, null, true),
  ('4', 'lovely', '愛らしい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'healthy', '健康な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'lucky', '運のよい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'handsome', 'ハンサムな', 'word', 'いろ・ようす', null, null, true),
  ('4', 'clever', 'りこうな', 'word', 'いろ・ようす', null, null, true),
  ('4', 'smart', '頭のいい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'lazy', 'なまけた', 'word', 'いろ・ようす', null, null, true),
  ('4', 'shy', 'はずかしがりの', 'word', 'いろ・ようす', null, null, true),
  ('4', 'kind', '親切な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'careful', '注意深い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'correct', '（答えなどが）正しい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'wrong', 'まちがった', 'word', 'いろ・ようす', null, null, true),
  ('4', 'true', '本当の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'real', '本物の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'own', '自分自身の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'front', '前の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'middle', 'まん中の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'foreign', '外国の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'boring', '退屈な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'broken', 'こわれた', 'word', 'いろ・ようす', null, null, true),
  ('4', 'safe', '安全な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'dangerous', '危険な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'popular', '人気のある', 'word', 'いろ・ようす', null, null, true),
  ('4', 'useful', '役に立つ', 'word', 'いろ・ようす', null, null, true),
  ('4', 'simple', '単純な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'empty', 'からっぽの', 'word', 'いろ・ようす', null, null, true),
  ('4', 'wet', 'ぬれた', 'word', 'いろ・ようす', null, null, true),
  ('4', 'soft', 'やわらかい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'hard', 'かたい、難しい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'quick', 'すばやい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'noisy', 'うるさい', 'word', 'いろ・ようす', null, null, true),
  ('4', 'fresh', '新鮮な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'fantastic', '最高の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'perfect', '完ぺきな', 'word', 'いろ・ようす', null, null, true),
  ('4', 'modern', '現代の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'traditional', '伝統的な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'international', '国際的な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'local', '地元の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'wild', '野生の', 'word', 'いろ・ようす', null, null, true),
  ('4', 'wide', '（はばが）広い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'low', '低い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'weak', '弱い', 'word', 'いろ・ようす', null, null, true),
  ('4', 'poor', '貧しい、かわいそうな', 'word', 'いろ・ようす', null, null, true),
  ('4', 'sure', '確かな', 'word', 'いろ・ようす', null, null, true),
  ('4', 'possible', '可能な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'impossible', '不可能な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'necessary', '必要な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'comfortable', '快適な', 'word', 'いろ・ようす', null, null, true),
  ('4', 'crowded', 'こんでいる', 'word', 'いろ・ようす', null, null, true),
  ('4', 'alive', '生きている', 'word', 'いろ・ようす', null, null, true),
  ('4', 'interested', '興味がある', 'word', 'きもち', null, null, true),
  ('4', 'bored', '退屈した', 'word', 'きもち', null, null, true),
  ('4', 'surprised', 'おどろいた', 'word', 'きもち', null, null, true),
  ('4', 'worried', '心配した', 'word', 'きもち', null, null, true),
  ('4', 'sleepy', 'ねむい', 'word', 'きもち', null, null, true),
  ('4', 'thirsty', 'のどがかわいた', 'word', 'きもち', null, null, true),
  ('4', 'nervous', '緊張した', 'word', 'きもち', null, null, true),
  ('4', 'pleased', '喜んだ', 'word', 'きもち', null, null, true),
  ('4', 'upset', '動揺した', 'word', 'きもち', null, null, true),
  ('4', 'disappointed', 'がっかりした', 'word', 'きもち', null, null, true),
  ('4', 'feeling', '気持ち', 'word', 'きもち', null, null, true),
  ('4', 'hope', '希望', 'word', 'きもち', null, null, true),
  ('4', 'wish', '願い', 'word', 'きもち', null, null, true),
  ('4', 'luck', '運', 'word', 'きもち', null, null, true),
  ('4', 'peace', '平和', 'word', 'きもち', null, null, true),
  ('4', 'surprise', 'おどろき', 'word', 'きもち', null, null, true),
  ('4', 'smile', 'ほほえみ', 'word', 'きもち', null, null, true),
  ('4', 'memory', '思い出、記憶', 'word', 'きもち', null, null, true),
  ('4', 'mind', '心、精神', 'word', 'きもち', null, null, true),
  ('4', 'friendship', '友情', 'word', 'きもち', null, null, true),
  ('4', 'happiness', '幸福', 'word', 'きもち', null, null, true),
  ('4', 'joy', '喜び', 'word', 'きもち', null, null, true),
  ('4', 'fear', 'おそれ', 'word', 'きもち', null, null, true),
  ('4', 'add', '加える', 'word', 'うごき', null, null, true),
  ('4', 'agree', '賛成する', 'word', 'うごき', null, null, true),
  ('4', 'arrive', '着く', 'word', 'うごき', null, null, true),
  ('4', 'become', '〜になる', 'word', 'うごき', null, null, true),
  ('4', 'begin', '始まる、始める', 'word', 'うごき', null, null, true),
  ('4', 'believe', '信じる', 'word', 'うごき', null, null, true),
  ('4', 'borrow', '借りる', 'word', 'うごき', null, null, true),
  ('4', 'lend', '貸す', 'word', 'うごき', null, null, true),
  ('4', 'break', 'こわす', 'word', 'うごき', null, null, true),
  ('4', 'bring', '持ってくる', 'word', 'うごき', null, null, true),
  ('4', 'build', '建てる', 'word', 'うごき', null, null, true),
  ('4', 'celebrate', '祝う', 'word', 'うごき', null, null, true),
  ('4', 'change', '変える', 'word', 'うごき', null, null, true),
  ('4', 'choose', '選ぶ', 'word', 'うごき', null, null, true),
  ('4', 'collect', '集める', 'word', 'うごき', null, null, true),
  ('4', 'cut', '切る', 'word', 'うごき', null, null, true),
  ('4', 'describe', '（ようすを）述べる', 'word', 'うごき', null, null, true),
  ('4', 'explain', '説明する', 'word', 'うごき', null, null, true),
  ('4', 'drop', '落とす', 'word', 'うごき', null, null, true),
  ('4', 'exercise', '運動する', 'word', 'うごき', null, null, true),
  ('4', 'feel', '感じる', 'word', 'うごき', null, null, true),
  ('4', 'fill', '満たす', 'word', 'うごき', null, null, true),
  ('4', 'forget', '忘れる', 'word', 'うごき', null, null, true),
  ('4', 'grow', '育つ、育てる', 'word', 'うごき', null, null, true),
  ('4', 'guess', '推測する', 'word', 'うごき', null, null, true),
  ('4', 'happen', '起こる', 'word', 'うごき', null, null, true),
  ('4', 'hide', 'かくれる、かくす', 'word', 'うごき', null, null, true),
  ('4', 'hurt', '傷つける、痛む', 'word', 'うごき', null, null, true),
  ('4', 'imagine', '想像する', 'word', 'うごき', null, null, true),
  ('4', 'introduce', '紹介する', 'word', 'うごき', null, null, true),
  ('4', 'join', '参加する、加わる', 'word', 'うごき', null, null, true),
  ('4', 'keep', '保つ、持ち続ける', 'word', 'うごき', null, null, true),
  ('4', 'laugh', '（声を出して）笑う', 'word', 'うごき', null, null, true),
  ('4', 'leave', '出発する、去る', 'word', 'うごき', null, null, true),
  ('4', 'lose', '失う、負ける', 'word', 'うごき', null, null, true),
  ('4', 'miss', '乗りおくれる、さびしく思う', 'word', 'うごき', null, null, true),
  ('4', 'pay', '（お金を）払う', 'word', 'うごき', null, null, true),
  ('4', 'pick', 'つむ、選ぶ', 'word', 'うごき', null, null, true),
  ('4', 'push', 'おす', 'word', 'うごき', null, null, true),
  ('4', 'pull', '引く', 'word', 'うごき', null, null, true),
  ('4', 'remember', '覚えている、思い出す', 'word', 'うごき', null, null, true),
  ('4', 'repeat', 'くり返す', 'word', 'うごき', null, null, true),
  ('4', 'save', '救う、節約する', 'word', 'うごき', null, null, true),
  ('4', 'send', '送る', 'word', 'うごき', null, null, true),
  ('4', 'share', '分け合う', 'word', 'うごき', null, null, true),
  ('4', 'show', '見せる', 'word', 'うごき', null, null, true),
  ('4', 'spend', '（時間を）過ごす、（お金を）使う', 'word', 'うごき', null, null, true),
  ('4', 'stay', '滞在する', 'word', 'うごき', null, null, true),
  ('4', 'travel', '旅行する', 'word', 'うごき', null, null, true),
  ('4', 'turn', '曲がる、回す', 'word', 'うごき', null, null, true),
  ('4', 'win', '勝つ', 'word', 'うごき', null, null, true),
  ('4', 'understand', '理解する', 'word', 'うごき', null, null, true),
  ('4', 'decide', '決める', 'word', 'うごき', null, null, true),
  ('4', 'invite', '招待する', 'word', 'うごき', null, null, true),
  ('4', 'hurry', '急ぐ', 'word', 'うごき', null, null, true),
  ('4', 'climb', '登る', 'word', 'うごき', null, null, true),
  ('4', 'cry', '泣く', 'word', 'うごき', null, null, true),
  ('4', 'fall', '落ちる', 'word', 'うごき', null, null, true),
  ('4', 'hold', '持つ、（会を）開く', 'word', 'うごき', null, null, true),
  ('4', 'move', '動く、引っ越す', 'word', 'うごき', null, null, true),
  ('4', 'return', 'もどる、返す', 'word', 'うごき', null, null, true),
  ('4', 'receive', '受け取る', 'word', 'うごき', null, null, true),
  ('4', 'try', 'やってみる', 'word', 'うごき', null, null, true),
  ('4', 'worry', '心配する', 'word', 'うごき', null, null, true),
  ('4', 'hate', '大きらいだ', 'word', 'うごき', null, null, true),
  ('4', 'prepare', '準備する', 'word', 'うごき', null, null, true),
  ('4', 'relax', 'くつろぐ', 'word', 'うごき', null, null, true),
  ('4', 'wonder', '〜かなと思う', 'word', 'うごき', null, null, true),
  ('4', 'check', '確かめる', 'word', 'うごき', null, null, true),
  ('4', 'cross', '渡る、横切る', 'word', 'うごき', null, null, true),
  ('4', 'enter', '入る', 'word', 'うごき', null, null, true),
  ('4', 'follow', 'ついていく', 'word', 'うごき', null, null, true),
  ('4', 'throw', '投げる', 'word', 'うごき', null, null, true),
  ('4', 'count', '数える', 'word', 'うごき', null, null, true),
  ('4', 'bake', '（オーブンで）焼く', 'word', 'うごき', null, null, true),
  ('4', 'boil', 'ゆでる、わかす', 'word', 'うごき', null, null, true),
  ('4', 'mix', '混ぜる', 'word', 'うごき', null, null, true),
  ('4', 'repair', '修理する', 'word', 'うごき', null, null, true),
  ('4', 'greet', 'あいさつする', 'word', 'うごき', null, null, true),
  ('4', 'thank', '感謝する', 'word', 'うごき', null, null, true),
  ('4', 'solve', '解く、解決する', 'word', 'うごき', null, null, true),
  ('4', 'seem', '〜のように見える', 'word', 'うごき', null, null, true),
  ('4', 'sound', '〜に聞こえる', 'word', 'うごき', null, null, true),
  ('4', 'about', '〜について', 'word', 'ことば', null, null, true),
  ('4', 'above', '〜の上の方に', 'word', 'ことば', null, null, true),
  ('4', 'across', '〜を横切って', 'word', 'ことば', null, null, true),
  ('4', 'along', '〜に沿って', 'word', 'ことば', null, null, true),
  ('4', 'around', '〜のまわりに', 'word', 'ことば', null, null, true),
  ('4', 'behind', '〜の後ろに', 'word', 'ことば', null, null, true),
  ('4', 'below', '〜より下に', 'word', 'ことば', null, null, true),
  ('4', 'beside', '〜のそばに', 'word', 'ことば', null, null, true),
  ('4', 'between', '（2つ）の間に', 'word', 'ことば', null, null, true),
  ('4', 'by', '〜のそばに、〜によって', 'word', 'ことば', null, null, true),
  ('4', 'for', '〜のために', 'word', 'ことば', null, null, true),
  ('4', 'into', '〜の中へ', 'word', 'ことば', null, null, true),
  ('4', 'of', '〜の', 'word', 'ことば', null, null, true),
  ('4', 'over', '〜の上に、〜をこえて', 'word', 'ことば', null, null, true),
  ('4', 'through', '〜を通りぬけて', 'word', 'ことば', null, null, true),
  ('4', 'to', '〜へ', 'word', 'ことば', null, null, true),
  ('4', 'during', '〜の間ずっと', 'word', 'ことば', null, null, true),
  ('4', 'without', '〜なしで', 'word', 'ことば', null, null, true),
  ('4', 'among', '（3つ以上）の中で', 'word', 'ことば', null, null, true),
  ('4', 'than', '〜よりも', 'word', 'ことば', null, null, true),
  ('4', 'almost', 'ほとんど', 'word', 'ことば', null, null, true),
  ('4', 'also', '〜もまた', 'word', 'ことば', null, null, true),
  ('4', 'already', 'すでに', 'word', 'ことば', null, null, true),
  ('4', 'alone', 'ひとりで', 'word', 'ことば', null, null, true),
  ('4', 'away', 'はなれて', 'word', 'ことば', null, null, true),
  ('4', 'back', 'もとへ、うしろへ', 'word', 'ことば', null, null, true),
  ('4', 'both', '両方', 'word', 'ことば', null, null, true),
  ('4', 'carefully', '注意深く', 'word', 'ことば', null, null, true),
  ('4', 'down', '下へ', 'word', 'ことば', null, null, true),
  ('4', 'up', '上へ', 'word', 'ことば', null, null, true),
  ('4', 'out', '外へ', 'word', 'ことば', null, null, true),
  ('4', 'outside', '外で', 'word', 'ことば', null, null, true),
  ('4', 'inside', '中で', 'word', 'ことば', null, null, true),
  ('4', 'everywhere', 'どこでも', 'word', 'ことば', null, null, true),
  ('4', 'just', 'ちょうど', 'word', 'ことば', null, null, true),
  ('4', 'maybe', 'たぶん', 'word', 'ことば', null, null, true),
  ('4', 'probably', 'おそらく', 'word', 'ことば', null, null, true),
  ('4', 'never', '決して〜ない', 'word', 'ことば', null, null, true),
  ('4', 'only', '〜だけ', 'word', 'ことば', null, null, true),
  ('4', 'once', '一度、かつて', 'word', 'ことば', null, null, true),
  ('4', 'quickly', 'すばやく', 'word', 'ことば', null, null, true),
  ('4', 'really', '本当に', 'word', 'ことば', null, null, true),
  ('4', 'sometimes', 'ときどき', 'word', 'ことば', null, null, true),
  ('4', 'straight', 'まっすぐに', 'word', 'ことば', null, null, true),
  ('4', 'then', 'そのとき、それから', 'word', 'ことば', null, null, true),
  ('4', 'well', '上手に', 'word', 'ことば', null, null, true),
  ('4', 'yet', '（否定文で）まだ', 'word', 'ことば', null, null, true),
  ('4', 'still', 'まだ、今でも', 'word', 'ことば', null, null, true),
  ('4', 'ever', '今までに', 'word', 'ことば', null, null, true),
  ('4', 'even', '〜でさえ', 'word', 'ことば', null, null, true),
  ('4', 'enough', '十分に', 'word', 'ことば', null, null, true),
  ('4', 'far', '遠くに', 'word', 'ことば', null, null, true),
  ('4', 'next', '次に', 'word', 'ことば', null, null, true),
  ('4', 'finally', 'ついに', 'word', 'ことば', null, null, true),
  ('4', 'easily', 'かんたんに', 'word', 'ことば', null, null, true),
  ('4', 'slowly', 'ゆっくりと', 'word', 'ことば', null, null, true),
  ('4', 'happily', '幸せに', 'word', 'ことば', null, null, true),
  ('4', 'all right', 'だいじょうぶな', 'word', 'かいわ', null, null, true),
  ('4', 'pardon', '（聞き返して）もう一度言ってください', 'word', 'かいわ', null, null, true),
  ('4', 'hey', 'ねえ、おい', 'word', 'かいわ', null, null, true),
  ('4', 'a piece of ～', '１つの～', 'phrase', 'かず', 'Can I have [[a piece of]] cake?', 'ケーキを[[1切れ]]もらえる？', true),
  ('4', 'on time', '時間通りに', 'phrase', 'じかん', 'The bus came [[on time]].', 'バスは[[時間通りに]]来た。', true),
  ('4', 'be afraid of ～', '～をこわがる', 'phrase', 'きもち', 'My sister [[is afraid of]] dogs.', '妹は犬を[[こわがっている]]。', true),
  ('4', 'be different from ～', '～とちがっている', 'phrase', 'いろ・ようす', 'My bag [[is different from]] yours.', '私のかばんはきみのと[[ちがう]]。', true),
  ('4', 'look for ～', '～をさがす', 'phrase', 'うごき', 'I''m [[looking for]] my key.', '私はかぎを[[さがしている]]。', true),
  ('4', 'hear from ～', '～から便りがある', 'phrase', 'うごき', 'I [[heard from]] my aunt yesterday.', 'きのう、おばから[[便りがあった]]。', true),
  ('4', 'grow up', '大人になる、育つ', 'phrase', 'うごき', 'I want to be a doctor when I [[grow up]].', '[[大人になったら]]医者になりたい。', true),
  ('4', 'put on ～', '～を身につける', 'phrase', 'うごき', '[[Put on]] your coat. It''s cold.', 'コートを[[着なさい]]。寒いよ。', true),
  ('4', 'try on ～', '～を試着する', 'phrase', 'うごき', 'Can I [[try on]] this shirt?', 'このシャツを[[試着して]]もいいですか。', true),
  ('4', 'turn on ～', '（スイッチなど）をつける', 'phrase', 'うごき', 'Please [[turn on]] the light.', '電気を[[つけて]]ください。', true),
  ('4', 'turn off ～', '（スイッチなど）を消す', 'phrase', 'うごき', '[[Turn off]] the TV, please.', 'テレビを[[消して]]ください。', true),
  ('4', 'take off ～', '～をぬぐ', 'phrase', 'うごき', 'Please [[take off]] your shoes here.', 'ここでくつを[[ぬいで]]ください。', true),
  ('4', 'make a mistake', 'まちがいをする', 'phrase', 'がっこう', 'Don''t worry if you [[make a mistake]].', '[[まちがえても]]心配しないで。', true),
  ('4', 'do one''s best', '最善をつくす', 'phrase', 'きもち', 'I will [[do my best]] in the game.', '試合で[[ベストをつくす]]よ。', true),
  ('4', 'enjoy oneself', '楽しい時を過ごす', 'phrase', 'きもち', 'We [[enjoyed ourselves]] at the party.', '私たちはパーティーで[[楽しく過ごした]]。', true),
  ('4', 'take care of ～', '～の世話をする', 'phrase', 'うごき', 'I [[take care of]] my dog every day.', '私は毎日、犬の[[世話をする]]。', true),
  ('4', 'look forward to ～', '～を楽しみに待つ', 'phrase', 'きもち', 'I''m [[looking forward to]] the trip.', '私は旅行を[[楽しみにしている]]。', true),
  ('4', 'by the way', 'ところで', 'phrase', 'かいわ', '[[By the way]], where is Tom?', '[[ところで]]、トムはどこ？', true),
  ('4', 'for example', 'たとえば', 'phrase', 'ことば', 'I like fruit, [[for example]], apples.', '私はくだもの、[[たとえば]]りんごが好き。', true),
  ('4', 'in the future', '将来は', 'phrase', 'じかん', 'I want to live abroad [[in the future]].', '[[将来は]]外国に住みたい。', true),
  ('4', 'each other', 'おたがい', 'phrase', 'かぞく・ひと', 'They help [[each other]].', '彼らは[[おたがいに]]助け合う。', true),
  ('4', 'at first', '最初は', 'phrase', 'じかん', '[[At first]], I didn''t like natto.', '[[最初は]]、納豆が好きじゃなかった。', true),
  ('4', 'for the first time', '初めて', 'phrase', 'じかん', 'I saw snow [[for the first time]].', '私は[[初めて]]雪を見た。', true),
  ('4', 'on the way (to ～)', '（～への）途中で', 'phrase', 'ばしょ', 'I met Ken [[on the way to]] school.', '学校へ行く[[途中で]]ケンに会った。', true),
  ('4', 'take a seat', 'すわる、席につく', 'phrase', 'うごき', 'Please [[take a seat]].', 'どうぞ[[おかけ]]ください。', true),
  ('4', 'shake hands', '握手する', 'phrase', 'かぞく・ひと', 'They [[shook hands]] after the game.', '彼らは試合のあと[[握手した]]。', true),
  ('4', 'make friends with ～', '～と友だちになる', 'phrase', 'かぞく・ひと', 'I [[made friends with]] a new student.', '私は転校生と[[友だちになった]]。', true),
  ('4', 'be busy with ～', '～でいそがしい', 'phrase', 'きもち', 'She [[is busy with]] her homework.', '彼女は宿題[[でいそがしい]]。', true),
  ('4', 'have a look at ～', '～を見る', 'phrase', 'うごき', 'Let me [[have a look at]] your picture.', 'きみの絵を[[見せて]]。', true),
  ('4', 'get on ～', '（乗り物）に乗る', 'phrase', 'うごき', 'We [[got on]] the train at Tokyo.', '私たちは東京で電車に[[乗った]]。', true),
  ('4', 'get off ～', '（乗り物）を降りる', 'phrase', 'うごき', '[[Get off]] the bus at the next stop.', '次のバス停でバスを[[降りて]]。', true),
  ('4', 'wait for ～', '～を待つ', 'phrase', 'うごき', 'I''m [[waiting for]] my mother.', '私は母を[[待っている]]。', true),
  ('4', 'look like ～', '～のように見える', 'phrase', 'いろ・ようす', 'That cloud [[looks like]] a fish.', 'あの雲は魚の[[ように見える]]。', true),
  ('4', 'be good at ～', '～が得意だ', 'phrase', 'きもち', 'Ken [[is good at]] soccer.', 'ケンはサッカーが[[得意だ]]。', true),
  ('4', 'come back', 'もどってくる', 'phrase', 'うごき', 'Please [[come back]] by five.', '5時までに[[もどってきて]]。', true),
  ('4', 'have a good time', '楽しく過ごす', 'phrase', 'あそび・スポーツ', 'We [[had a good time]] at the beach.', '私たちは浜辺で[[楽しく過ごした]]。', true),
  ('4', 'talk with ～', '～と話す', 'phrase', 'うごき', 'I [[talked with]] my teacher after class.', '授業のあと先生[[と話した]]。', true),
  ('4', 'arrive at ～', '～に着く', 'phrase', 'うごき', 'We [[arrived at]] the station at noon.', '私たちは正午に駅[[に着いた]]。', true),
  ('4', 'all day', '一日中', 'phrase', 'じかん', 'It rained [[all day]].', '[[一日中]]雨がふった。', true),
  ('4', 'What ～ like?', '～はどんなようす？', 'idiom', 'かいわ', '"[[What is it like?]]" "It''s big and red."', '「[[それってどんな感じ？]]」「大きくて赤いよ。」', true),
  ('4', 'Take it easy.', '気楽にね。', 'idiom', 'かいわ', '"I''m nervous about the test." "[[Take it easy.]]"', '「テストが心配だよ。」「[[気楽にね。]]」', true),
  ('4', 'My pleasure.', 'どういたしまして（喜んで）。', 'idiom', 'かいわ', '"Thanks for your help." "[[My pleasure.]]"', '「手伝ってくれてありがとう。」「[[どういたしまして。]]」', true),
  ('4', 'Here we are.', 'さあ、着いた。', 'idiom', 'かいわ', '"[[Here we are.]] This is the zoo."', '「[[さあ、着いたよ。]]ここが動物園だ。」', true),
  ('4', 'Go ahead.', 'どうぞ。', 'idiom', 'かいわ', '"Can I use your pen?" "Sure. [[Go ahead.]]"', '「ペンを使ってもいい？」「いいよ。[[どうぞ。]]」', true),
  ('4', 'Can I help you?', 'いらっしゃいませ（お手伝いしましょうか）。', 'idiom', 'かいわ', '"[[Can I help you?]]" "I''m looking for a cap."', '「[[いらっしゃいませ。]]」「ぼうしをさがしています。」', true),
  ('4', 'I''d like ～.', '～がほしいのですが。', 'idiom', 'かいわ', '"[[I''d like]] a hamburger, please."', '「ハンバーガーを[[ください]]。」', true),
  ('4', 'How about ～?', '～はどう？', 'idiom', 'かいわ', '"[[How about]] going to the park?"', '「公園に行くのは[[どう？]]」', true),
  ('4', 'That''s too bad.', 'それはお気の毒に。', 'idiom', 'かいわ', '"I have a cold." "[[That''s too bad.]]"', '「かぜをひいたんだ。」「[[それはお気の毒に。]]」', true),
  ('4', 'No problem.', '問題ないよ。', 'idiom', 'かいわ', '"Can you help me?" "[[No problem.]]"', '「手伝ってくれる？」「[[問題ないよ。]]」', true),
  ('4', 'Don''t worry.', '心配しないで。', 'idiom', 'かいわ', '"I lost my pen." "[[Don''t worry.]] Use mine."', '「ペンをなくしちゃった。」「[[心配しないで。]]ぼくのを使って。」', true),
  ('4', 'What''s wrong?', 'どうしたの？', 'idiom', 'かいわ', '"[[What''s wrong?]]" "I have a headache."', '「[[どうしたの？]]」「頭が痛いんだ。」', true),
  ('4', 'Have a nice day.', 'よい一日を。', 'idiom', 'かいわ', '"See you later." "[[Have a nice day.]]"', '「またあとでね。」「[[よい一日を。]]」', true),
  ('4', 'Long time no see.', '久しぶり。', 'idiom', 'かいわ', '"Hi, Ken! [[Long time no see.]]"', '「やあ、ケン！[[久しぶり。]]」', true),
  ('4', 'Why don''t we ～?', '～しませんか。', 'idiom', 'かいわ', '"[[Why don''t we]] have lunch together?"', '「いっしょにお昼を[[食べませんか。]]」', true),
  ('4', 'Sure.', 'もちろん、いいよ。', 'idiom', 'かいわ', '"Can I sit here?" "[[Sure.]]"', '「ここにすわってもいい？」「[[いいよ。]]」', true),
  ('4', 'Hold on.', '（電話で）少々お待ちください。', 'idiom', 'かいわ', '"Is Emi there?" "[[Hold on]], please."', '「エミはいますか。」「[[少々お待ち]]ください。」', true),
  ('4', 'Speaking.', '（電話で）私です。', 'idiom', 'かいわ', '"Can I speak to Ken?" "[[Speaking.]]"', '「ケンをお願いします。」「[[ぼくです。]]」', true),
  ('4', 'Congratulations!', 'おめでとう！', 'idiom', 'かいわ', '"I won the contest!" "[[Congratulations!]]"', '「コンテストで優勝したよ！」「[[おめでとう！]]」', true)
on conflict (level, en) do update set
  ja = excluded.ja, type = excluded.type, theme = excluded.theme,
  example_en = excluded.example_en, example_ja = excluded.example_ja, active = true;
commit;
