-- 3級の語彙（645語）。scripts/vocab/build-seed.mjs で vocab_3.tsv から生成。手で編集しない。
-- 単語の選定は CEFR-J Wordlist Version 1.6（東京外国語大学投野由紀夫研究室）を元にしている。
-- Supabase の SQL Editor で実行する。同じ (level, en) があれば内容を上書きし、id は変えない（記録を壊さない）。
begin;
insert into public.vocab_items (level, en, ja, type, theme, example_en, example_ja, active) values
  ('3', 'cereal', 'シリアル', 'word', 'たべもの', null, null, true),
  ('3', 'garlic', 'にんにく', 'word', 'たべもの', null, null, true),
  ('3', 'flour', '小麦粉', 'word', 'たべもの', null, null, true),
  ('3', 'oil', '油', 'word', 'たべもの', null, null, true),
  ('3', 'sauce', 'ソース', 'word', 'たべもの', null, null, true),
  ('3', 'pasta', 'パスタ', 'word', 'たべもの', null, null, true),
  ('3', 'omelet', 'オムレツ', 'word', 'たべもの', null, null, true),
  ('3', 'pea', 'えんどう豆', 'word', 'たべもの', null, null, true),
  ('3', 'slice', 'うすい1切れ', 'word', 'たべもの', null, null, true),
  ('3', 'lemonade', 'レモネード', 'word', 'たべもの', null, null, true),
  ('3', 'supper', '（軽めの）夕食', 'word', 'たべもの', null, null, true),
  ('3', 'fast food', 'ファストフード', 'word', 'たべもの', null, null, true),
  ('3', 'cooking', '料理（すること）', 'word', 'たべもの', null, null, true),
  ('3', 'oven', 'オーブン', 'word', 'たべもの', null, null, true),
  ('3', 'pan', 'フライパン、なべ', 'word', 'たべもの', null, null, true),
  ('3', 'napkin', 'ナプキン', 'word', 'たべもの', null, null, true),
  ('3', 'mug', 'マグカップ', 'word', 'たべもの', null, null, true),
  ('3', 'fried', '油であげた', 'word', 'たべもの', null, null, true),
  ('3', 'raw', '生の', 'word', 'たべもの', null, null, true),
  ('3', 'boiled', 'ゆでた', 'word', 'たべもの', null, null, true),
  ('3', 'barbecue', 'バーベキュー', 'word', 'たべもの', null, null, true),
  ('3', 'diet', 'ふだんの食事、ダイエット', 'word', 'たべもの', null, null, true),
  ('3', 'chimpanzee', 'チンパンジー', 'word', 'どうぶつ', null, null, true),
  ('3', 'creature', '生き物', 'word', 'どうぶつ', null, null, true),
  ('3', 'feather', '羽', 'word', 'どうぶつ', null, null, true),
  ('3', 'bug', '（小さな）虫', 'word', 'どうぶつ', null, null, true),
  ('3', 'shell', '貝がら、から', 'word', 'どうぶつ', null, null, true),
  ('3', 'endangered', '絶滅のおそれがある', 'word', 'どうぶつ', null, null, true),
  ('3', 'grandchild', '孫', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'couple', '夫婦、カップル', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'ancestor', '先祖', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'citizen', '市民', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'athlete', '運動選手', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'astronaut', '宇宙飛行士', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'author', '著者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'boss', '上司', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'chef', 'シェフ', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'clerk', '店員、事務員', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'composer', '作曲家', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'director', '監督', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'editor', '編集者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'expert', '専門家', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'guard', '警備員', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'host', '（客をもてなす）主人', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'lawyer', '弁護士', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'manager', '支配人、管理者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'patient', '患者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'photographer', '写真家', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'secretary', '秘書', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'soldier', '兵士', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'winner', '勝者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'beginner', '初心者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'audience', '観客、聴衆', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'crowd', '群衆、人ごみ', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'staff', '職員、スタッフ', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'traveler', '旅行者', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'tour guide', 'ツアーガイド', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'receptionist', '受付係', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'fisherman', '漁師', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'lady', '婦人', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'guy', '男の人、やつ', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'foreigner', '外国人', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'angel', '天使', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'fairy', '妖精', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'ghost', 'おばけ', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'youth', '若者、青春時代', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'personality', '性格、個性', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'character', '登場人物、性格', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'generation', '世代', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'society', '社会', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'population', '人口', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'nation', '国家、国民', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'public', '一般の人々', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'elderly', 'お年寄りの', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'senior', '年上の', 'word', 'かぞく・ひと', null, null, true),
  ('3', 'ankle', '足首', 'word', 'からだ', null, null, true),
  ('3', 'chest', '胸', 'word', 'からだ', null, null, true),
  ('3', 'chin', 'あご', 'word', 'からだ', null, null, true),
  ('3', 'tear', '涙', 'word', 'からだ', null, null, true),
  ('3', 'ill', '（重い）病気の', 'word', 'からだ', null, null, true),
  ('3', 'injure', 'けがをさせる', 'word', 'からだ', null, null, true),
  ('3', 'pill', '錠剤', 'word', 'からだ', null, null, true),
  ('3', 'dizzy', 'めまいがする', 'word', 'からだ', null, null, true),
  ('3', 'breathe', '呼吸する', 'word', 'からだ', null, null, true),
  ('3', 'weight', '体重、重さ', 'word', 'からだ', null, null, true),
  ('3', 'overweight', '太りすぎの', 'word', 'からだ', null, null, true),
  ('3', 'chapter', '（本の）章', 'word', 'がっこう', null, null, true),
  ('3', 'essay', '作文、エッセイ', 'word', 'がっこう', null, null, true),
  ('3', 'title', '題名', 'word', 'がっこう', null, null, true),
  ('3', 'novel', '小説', 'word', 'がっこう', null, null, true),
  ('3', 'text', '文章、本文', 'word', 'がっこう', null, null, true),
  ('3', 'research', '研究', 'word', 'がっこう', null, null, true),
  ('3', 'education', '教育', 'word', 'がっこう', null, null, true),
  ('3', 'knowledge', '知識', 'word', 'がっこう', null, null, true),
  ('3', 'meaning', '意味', 'word', 'がっこう', null, null, true),
  ('3', 'expression', '表現、表情', 'word', 'がっこう', null, null, true),
  ('3', 'explanation', '説明', 'word', 'がっこう', null, null, true),
  ('3', 'opinion', '意見', 'word', 'がっこう', null, null, true),
  ('3', 'discussion', '話し合い', 'word', 'がっこう', null, null, true),
  ('3', 'debate', '討論', 'word', 'がっこう', null, null, true),
  ('3', 'argument', '口論、議論', 'word', 'がっこう', null, null, true),
  ('3', 'schoolwork', '学校の勉強', 'word', 'がっこう', null, null, true),
  ('3', 'semester', '学期', 'word', 'がっこう', null, null, true),
  ('3', 'campus', '（大学の）キャンパス', 'word', 'がっこう', null, null, true),
  ('3', 'college', '（単科）大学、専門学校', 'word', 'がっこう', null, null, true),
  ('3', 'course', '講座、コース', 'word', 'がっこう', null, null, true),
  ('3', 'level', '水準、レベル', 'word', 'がっこう', null, null, true),
  ('3', 'skill', '技能、うでまえ', 'word', 'がっこう', null, null, true),
  ('3', 'ability', '能力', 'word', 'がっこう', null, null, true),
  ('3', 'talent', '才能', 'word', 'がっこう', null, null, true),
  ('3', 'intelligence', '知能', 'word', 'がっこう', null, null, true),
  ('3', 'imagination', '想像力', 'word', 'がっこう', null, null, true),
  ('3', 'creativity', '創造力', 'word', 'がっこう', null, null, true),
  ('3', 'invention', '発明', 'word', 'がっこう', null, null, true),
  ('3', 'experience', '経験', 'word', 'がっこう', null, null, true),
  ('3', 'detail', '細かい点', 'word', 'がっこう', null, null, true),
  ('3', 'fact', '事実', 'word', 'がっこう', null, null, true),
  ('3', 'truth', '真実', 'word', 'がっこう', null, null, true),
  ('3', 'secret', '秘密', 'word', 'がっこう', null, null, true),
  ('3', 'mystery', 'なぞ', 'word', 'がっこう', null, null, true),
  ('3', 'clue', '手がかり', 'word', 'がっこう', null, null, true),
  ('3', 'symbol', '象徴、記号', 'word', 'がっこう', null, null, true),
  ('3', 'pronunciation', '発音', 'word', 'がっこう', null, null, true),
  ('3', 'noun', '名詞', 'word', 'がっこう', null, null, true),
  ('3', 'verb', '動詞', 'word', 'がっこう', null, null, true),
  ('3', 'adjective', '形容詞', 'word', 'がっこう', null, null, true),
  ('3', 'conversation', '会話', 'word', 'がっこう', null, null, true),
  ('3', 'article', '（新聞などの）記事', 'word', 'がっこう', null, null, true),
  ('3', 'paragraph', '段落', 'word', 'がっこう', null, null, true),
  ('3', 'topic', '話題', 'word', 'がっこう', null, null, true),
  ('3', 'survey', '調査', 'word', 'がっこう', null, null, true),
  ('3', 'interview', 'インタビュー、面接', 'word', 'がっこう', null, null, true),
  ('3', 'competition', '競争、大会', 'word', 'がっこう', null, null, true),
  ('3', 'award', '賞', 'word', 'がっこう', null, null, true),
  ('3', 'medal', 'メダル', 'word', 'がっこう', null, null, true),
  ('3', 'championship', '選手権', 'word', 'がっこう', null, null, true),
  ('3', 'area', '地域', 'word', 'ばしょ', null, null, true),
  ('3', 'capital', '首都', 'word', 'ばしょ', null, null, true),
  ('3', 'center', '中心', 'word', 'ばしょ', null, null, true),
  ('3', 'coast', '海岸', 'word', 'ばしょ', null, null, true),
  ('3', 'continent', '大陸', 'word', 'ばしょ', null, null, true),
  ('3', 'desert', '砂漠', 'word', 'ばしょ', null, null, true),
  ('3', 'valley', '谷', 'word', 'ばしょ', null, null, true),
  ('3', 'planet', '惑星', 'word', 'ばしょ', null, null, true),
  ('3', 'globe', '地球儀', 'word', 'ばしょ', null, null, true),
  ('3', 'path', '小道', 'word', 'ばしょ', null, null, true),
  ('3', 'highway', '幹線道路', 'word', 'ばしょ', null, null, true),
  ('3', 'gate', '門', 'word', 'ばしょ', null, null, true),
  ('3', 'entrance', '入り口', 'word', 'ばしょ', null, null, true),
  ('3', 'garage', '車庫', 'word', 'ばしょ', null, null, true),
  ('3', 'gallery', '画廊、美術館', 'word', 'ばしょ', null, null, true),
  ('3', 'mall', 'ショッピングモール', 'word', 'ばしょ', null, null, true),
  ('3', 'cafeteria', 'カフェテリア', 'word', 'ばしょ', null, null, true),
  ('3', 'cafe', '喫茶店、カフェ', 'word', 'ばしょ', null, null, true),
  ('3', 'bank', '銀行', 'word', 'ばしょ', null, null, true),
  ('3', 'seaside', '海辺', 'word', 'ばしょ', null, null, true),
  ('3', 'shore', '岸', 'word', 'ばしょ', null, null, true),
  ('3', 'roof', '屋根', 'word', 'ばしょ', null, null, true),
  ('3', 'balcony', 'バルコニー', 'word', 'ばしょ', null, null, true),
  ('3', 'stair', '階段（の1段）', 'word', 'ばしょ', null, null, true),
  ('3', 'elevator', 'エレベーター', 'word', 'ばしょ', null, null, true),
  ('3', 'escalator', 'エスカレーター', 'word', 'ばしょ', null, null, true),
  ('3', 'downtown', '繁華街で、町の中心部へ', 'word', 'ばしょ', null, null, true),
  ('3', 'upstairs', '上の階へ', 'word', 'ばしょ', null, null, true),
  ('3', 'downstairs', '下の階へ', 'word', 'ばしょ', null, null, true),
  ('3', 'overseas', '海外へ、海外で', 'word', 'ばしょ', null, null, true),
  ('3', 'anywhere', 'どこでも、どこかに', 'word', 'ばしょ', null, null, true),
  ('3', 'somewhere', 'どこかで', 'word', 'ばしょ', null, null, true),
  ('3', 'kingdom', '王国', 'word', 'ばしょ', null, null, true),
  ('3', 'state', '州、状態', 'word', 'ばしょ', null, null, true),
  ('3', 'scene', '場面', 'word', 'ばしょ', null, null, true),
  ('3', 'scenery', '景色', 'word', 'ばしょ', null, null, true),
  ('3', 'view', 'ながめ、見方', 'word', 'ばしょ', null, null, true),
  ('3', 'landscape', '風景', 'word', 'ばしょ', null, null, true),
  ('3', 'traffic', '交通', 'word', 'ばしょ', null, null, true),
  ('3', 'traffic light', '信号機', 'word', 'ばしょ', null, null, true),
  ('3', 'grocery store', '食料品店', 'word', 'ばしょ', null, null, true),
  ('3', 'drugstore', 'ドラッグストア', 'word', 'ばしょ', null, null, true),
  ('3', 'court', '（テニスなどの）コート、裁判所', 'word', 'ばしょ', null, null, true),
  ('3', 'alarm clock', '目覚まし時計', 'word', 'もの', null, null, true),
  ('3', 'basket', 'かご', 'word', 'もの', null, null, true),
  ('3', 'belt', 'ベルト', 'word', 'もの', null, null, true),
  ('3', 'bench', 'ベンチ', 'word', 'もの', null, null, true),
  ('3', 'bookshelf', '本だな', 'word', 'もの', null, null, true),
  ('3', 'comb', 'くし', 'word', 'もの', null, null, true),
  ('3', 'container', '容器', 'word', 'もの', null, null, true),
  ('3', 'cupboard', '食器だな', 'word', 'もの', null, null, true),
  ('3', 'drawer', '引き出し', 'word', 'もの', null, null, true),
  ('3', 'envelope', '封筒', 'word', 'もの', null, null, true),
  ('3', 'furniture', '家具', 'word', 'もの', null, null, true),
  ('3', 'handbag', 'ハンドバッグ', 'word', 'もの', null, null, true),
  ('3', 'headphone', 'ヘッドホン', 'word', 'もの', null, null, true),
  ('3', 'ID card', '身分証明書', 'word', 'もの', null, null, true),
  ('3', 'lock', '錠、ロック', 'word', 'もの', null, null, true),
  ('3', 'metal', '金属', 'word', 'もの', null, null, true),
  ('3', 'plastic', 'プラスチックの', 'word', 'もの', null, null, true),
  ('3', 'rope', 'ロープ、なわ', 'word', 'もの', null, null, true),
  ('3', 'screen', '画面、スクリーン', 'word', 'もの', null, null, true),
  ('3', 'software', 'ソフトウェア', 'word', 'もの', null, null, true),
  ('3', 'sunglasses', 'サングラス', 'word', 'もの', null, null, true),
  ('3', 'tie', 'ネクタイ', 'word', 'もの', null, null, true),
  ('3', 'wood', '木材、森', 'word', 'もの', null, null, true),
  ('3', 'wool', '羊毛', 'word', 'もの', null, null, true),
  ('3', 'diamond', 'ダイヤモンド', 'word', 'もの', null, null, true),
  ('3', 'crown', '王冠', 'word', 'もの', null, null, true),
  ('3', 'gas', 'ガス', 'word', 'もの', null, null, true),
  ('3', 'tape', 'テープ', 'word', 'もの', null, null, true),
  ('3', 'string', 'ひも', 'word', 'もの', null, null, true),
  ('3', 'washing machine', '洗濯機', 'word', 'もの', null, null, true),
  ('3', 'website', 'ウェブサイト', 'word', 'もの', null, null, true),
  ('3', 'Internet', 'インターネット', 'word', 'もの', null, null, true),
  ('3', 'text message', '（携帯電話の）メッセージ', 'word', 'もの', null, null, true),
  ('3', 'mobile phone', '携帯電話', 'word', 'もの', null, null, true),
  ('3', 'digital camera', 'デジタルカメラ', 'word', 'もの', null, null, true),
  ('3', 'program', '番組、計画', 'word', 'もの', null, null, true),
  ('3', 'product', '製品', 'word', 'もの', null, null, true),
  ('3', 'material', '材料', 'word', 'もの', null, null, true),
  ('3', 'chain', 'くさり', 'word', 'もの', null, null, true),
  ('3', 'balloon', '風船', 'word', 'もの', null, null, true),
  ('3', 'receipt', 'レシート、領収書', 'word', 'もの', null, null, true),
  ('3', 'cash', '現金', 'word', 'もの', null, null, true),
  ('3', 'bill', '請求書、お札', 'word', 'もの', null, null, true),
  ('3', 'fare', '（乗り物の）運賃', 'word', 'もの', null, null, true),
  ('3', 'fee', '料金、謝礼', 'word', 'もの', null, null, true),
  ('3', 'budget', '予算', 'word', 'もの', null, null, true),
  ('3', 'adventure', '冒険', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'camping', 'キャンプをすること', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'cycling', 'サイクリング', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'climbing', '登山', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'hockey', 'ホッケー', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'rugby', 'ラグビー', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'snowboarding', 'スノーボード', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'surfing', 'サーフィン', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'walking', '散歩、歩くこと', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'board game', 'ボードゲーム', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'cruise', '船旅', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'journey', '（長い）旅', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'flight', '（飛行機の）便、飛行', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'exhibition', '展覧会', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'performance', '演技、公演', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'entertainment', '娯楽', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'fashion', '流行、ファッション', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'leisure', '余暇', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'wedding', '結婚式', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'anniversary', '記念日', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'celebration', 'お祝い', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'joke', '冗談', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'classical music', 'クラシック音楽', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'rhythm', 'リズム', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'photography', '写真撮影', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'painting', '（絵の具でかいた）絵', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'drawing', '（線でかいた）絵、スケッチ', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'horror', '恐怖、ホラー', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'romance', '恋愛（の物語）', 'word', 'あそび・スポーツ', null, null, true),
  ('3', 'breeze', 'そよ風', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'flood', '洪水', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'earthquake', '地震', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'thunderstorm', '雷雨', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'heat', '暑さ、熱', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'shade', '日かげ', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'shadow', '影', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'bloom', '（咲いている）花', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'branch', '枝', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'bush', 'しげみ', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'root', '根', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'harvest', '収穫', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'rock', '岩', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'dust', 'ほこり、ちり', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'pollution', '汚染', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'natural', '自然の', 'word', 'しぜん・てんき', null, null, true),
  ('3', 'beginning', '始まり', 'word', 'じかん', null, null, true),
  ('3', 'ending', '結末', 'word', 'じかん', null, null, true),
  ('3', 'childhood', '子ども時代', 'word', 'じかん', null, null, true),
  ('3', 'lunchtime', '昼食の時間', 'word', 'じかん', null, null, true),
  ('3', 'timetable', '時刻表、時間割', 'word', 'じかん', null, null, true),
  ('3', 'delay', '遅れ', 'word', 'じかん', null, null, true),
  ('3', 'recently', '最近', 'word', 'じかん', null, null, true),
  ('3', 'nowadays', '近ごろは', 'word', 'じかん', null, null, true),
  ('3', 'someday', '（未来の）いつか', 'word', 'じかん', null, null, true),
  ('3', 'forever', '永遠に', 'word', 'じかん', null, null, true),
  ('3', 'twice', '2回、2倍', 'word', 'じかん', null, null, true),
  ('3', 'daily', '毎日の', 'word', 'じかん', null, null, true),
  ('3', 'weekly', '毎週の', 'word', 'じかん', null, null, true),
  ('3', 'recent', '最近の', 'word', 'じかん', null, null, true),
  ('3', 'latest', '最新の', 'word', 'じかん', null, null, true),
  ('3', 'final', '最後の', 'word', 'じかん', null, null, true),
  ('3', 'ancient', '古代の', 'word', 'じかん', null, null, true),
  ('3', 'past', '過去', 'word', 'じかん', null, null, true),
  ('3', 'age', '年齢、時代', 'word', 'じかん', null, null, true),
  ('3', 'centimeter', 'センチメートル', 'word', 'かず', null, null, true),
  ('3', 'kilometer', 'キロメートル', 'word', 'かず', null, null, true),
  ('3', 'kilogram', 'キログラム', 'word', 'かず', null, null, true),
  ('3', 'gram', 'グラム', 'word', 'かず', null, null, true),
  ('3', 'meter', 'メートル', 'word', 'かず', null, null, true),
  ('3', 'liter', 'リットル', 'word', 'かず', null, null, true),
  ('3', 'inch', 'インチ', 'word', 'かず', null, null, true),
  ('3', 'cent', 'セント', 'word', 'かず', null, null, true),
  ('3', 'euro', 'ユーロ', 'word', 'かず', null, null, true),
  ('3', 'average', '平均', 'word', 'かず', null, null, true),
  ('3', 'double', '2倍の', 'word', 'かず', null, null, true),
  ('3', 'pair', '1組、1対', 'word', 'かず', null, null, true),
  ('3', 'piece', '1つ、かけら', 'word', 'かず', null, null, true),
  ('3', 'plenty', 'たくさん', 'word', 'かず', null, null, true),
  ('3', 'plus', '〜を加えて', 'word', 'かず', null, null, true),
  ('3', 'rate', '割合、料金', 'word', 'かず', null, null, true),
  ('3', 'degree', '（温度・角度の）度', 'word', 'かず', null, null, true),
  ('3', 'cost', '（費用が）かかる', 'word', 'かず', null, null, true),
  ('3', 'colorful', '色あざやかな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'attractive', '魅力的な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'brave', '勇かんな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'brilliant', '見事な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'certain', '確実な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'clear', 'はっきりした、晴れた', 'word', 'いろ・ようす', null, null, true),
  ('3', 'common', 'ありふれた、共通の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'complete', '完全な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'confident', '自信のある', 'word', 'いろ・ようす', null, null, true),
  ('3', 'convenient', '便利な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'crazy', '夢中な、ばかげた', 'word', 'いろ・ようす', null, null, true),
  ('3', 'creative', '創造的な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'direct', 'まっすぐな、直接の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'electric', '電気の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'enormous', '巨大な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'familiar', 'よく知っている', 'word', 'いろ・ようす', null, null, true),
  ('3', 'fancy', 'しゃれた', 'word', 'いろ・ようす', null, null, true),
  ('3', 'fascinating', 'とても興味深い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'female', '女性の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'fit', '体調のよい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'gentle', 'おだやかな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'good-looking', '顔立ちのよい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'helpful', '助けになる', 'word', 'いろ・ようす', null, null, true),
  ('3', 'human', '人間の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'intelligent', '知能の高い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'likely', '〜しそうな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'lively', '元気いっぱいの', 'word', 'いろ・ようす', null, null, true),
  ('3', 'lost', '道に迷った、なくした', 'word', 'いろ・ようす', null, null, true),
  ('3', 'mysterious', 'なぞめいた', 'word', 'いろ・ようす', null, null, true),
  ('3', 'national', '国の、国民の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'native', '生まれた土地の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'normal', '標準の、正常な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'official', '公式の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'opposite', '反対の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'original', 'もとの、独創的な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'peaceful', '平和な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'pleasant', '心地よい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'polite', 'ていねいな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'powerful', '強力な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'private', '個人的な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'professional', 'プロの', 'word', 'いろ・ようす', null, null, true),
  ('3', 'regular', '規則正しい、ふだんの', 'word', 'いろ・ようす', null, null, true),
  ('3', 'rude', '失礼な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'similar', '似ている', 'word', 'いろ・ようす', null, null, true),
  ('3', 'single', 'たった1つの、独身の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'silly', 'ばかな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'smooth', 'なめらかな', 'word', 'いろ・ようす', null, null, true),
  ('3', 'sudden', '突然の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'suitable', '適した', 'word', 'いろ・ようす', null, null, true),
  ('3', 'surprising', 'おどろくべき', 'word', 'いろ・ようす', null, null, true),
  ('3', 'unusual', 'めずらしい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'usual', 'いつもの', 'word', 'いろ・ようす', null, null, true),
  ('3', 'whole', '全体の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'wise', '賢い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'wooden', '木でできた', 'word', 'いろ・ようす', null, null, true),
  ('3', 'ugly', 'みにくい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'strict', '厳しい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'successful', '成功した', 'word', 'いろ・ようす', null, null, true),
  ('3', 'unhappy', '不幸な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'unfair', '不公平な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'unknown', '知られていない', 'word', 'いろ・ようす', null, null, true),
  ('3', 'well-known', 'よく知られた', 'word', 'いろ・ようす', null, null, true),
  ('3', 'worse', 'より悪い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'worst', '最も悪い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'better', 'よりよい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'best', '最もよい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'awful', 'ものすごく悪い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'basic', '基本的な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'deep', '深い', 'word', 'いろ・ようす', null, null, true),
  ('3', 'extra', '余分の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'asleep', 'ねむって', 'word', 'いろ・ようす', null, null, true),
  ('3', 'awake', '目がさめて', 'word', 'いろ・ようす', null, null, true),
  ('3', 'false', '誤りの、うその', 'word', 'いろ・ようす', null, null, true),
  ('3', 'tight', 'きつい', 'word', 'いろ・ようす', null, null, true),
  ('3', 'fair', '公平な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'ideal', '理想的な', 'word', 'いろ・ようす', null, null, true),
  ('3', 'social', '社会の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'everyday', '日常の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'elementary', '初歩の、初等の', 'word', 'いろ・ようす', null, null, true),
  ('3', 'dear', '親愛なる', 'word', 'いろ・ようす', null, null, true),
  ('3', 'closed', '閉まった', 'word', 'いろ・ようす', null, null, true),
  ('3', 'anxious', '不安な', 'word', 'きもち', null, null, true),
  ('3', 'confused', '混乱した', 'word', 'きもち', null, null, true),
  ('3', 'embarrassing', 'はずかしい（ような）', 'word', 'きもち', null, null, true),
  ('3', 'frightened', 'おびえた', 'word', 'きもち', null, null, true),
  ('3', 'grateful', '感謝している', 'word', 'きもち', null, null, true),
  ('3', 'relaxed', 'くつろいだ', 'word', 'きもち', null, null, true),
  ('3', 'impatient', 'がまんできない', 'word', 'きもち', null, null, true),
  ('3', 'attention', '注意', 'word', 'きもち', null, null, true),
  ('3', 'advice', '助言', 'word', 'きもち', null, null, true),
  ('3', 'pity', '残念なこと、あわれみ', 'word', 'きもち', null, null, true),
  ('3', 'pride', 'ほこり（自分をほこらしく思う気持ち）', 'word', 'きもち', null, null, true),
  ('3', 'mood', '気分', 'word', 'きもち', null, null, true),
  ('3', 'sense', '感覚', 'word', 'きもち', null, null, true),
  ('3', 'doubt', '疑い', 'word', 'きもち', null, null, true),
  ('3', 'chance', '機会、見こみ', 'word', 'きもち', null, null, true),
  ('3', 'opportunity', '（よい）機会', 'word', 'きもち', null, null, true),
  ('3', 'purpose', '目的', 'word', 'きもち', null, null, true),
  ('3', 'success', '成功', 'word', 'きもち', null, null, true),
  ('3', 'effort', '努力', 'word', 'きもち', null, null, true),
  ('3', 'trouble', '困ったこと', 'word', 'きもち', null, null, true),
  ('3', 'danger', '危険', 'word', 'きもち', null, null, true),
  ('3', 'freedom', '自由', 'word', 'きもち', null, null, true),
  ('3', 'interest', '興味', 'word', 'きもち', null, null, true),
  ('3', 'thought', '考え', 'word', 'きもち', null, null, true),
  ('3', 'promise', '約束', 'word', 'きもち', null, null, true),
  ('3', 'accept', '受け入れる', 'word', 'うごき', null, null, true),
  ('3', 'achieve', '達成する', 'word', 'うごき', null, null, true),
  ('3', 'admire', '感心する', 'word', 'うごき', null, null, true),
  ('3', 'advise', '忠告する', 'word', 'うごき', null, null, true),
  ('3', 'allow', '許す', 'word', 'うごき', null, null, true),
  ('3', 'apologize', 'あやまる', 'word', 'うごき', null, null, true),
  ('3', 'appear', '現れる', 'word', 'うごき', null, null, true),
  ('3', 'argue', '言い争う', 'word', 'うごき', null, null, true),
  ('3', 'avoid', 'さける', 'word', 'うごき', null, null, true),
  ('3', 'belong', '属する', 'word', 'うごき', null, null, true),
  ('3', 'blame', '責める', 'word', 'うごき', null, null, true),
  ('3', 'bother', '迷惑をかける', 'word', 'うごき', null, null, true),
  ('3', 'cause', '引き起こす', 'word', 'うごき', null, null, true),
  ('3', 'chat', 'おしゃべりする', 'word', 'うごき', null, null, true),
  ('3', 'cheer', '声援を送る', 'word', 'うごき', null, null, true),
  ('3', 'communicate', '意思を伝え合う', 'word', 'うごき', null, null, true),
  ('3', 'compare', '比べる', 'word', 'うごき', null, null, true),
  ('3', 'complain', '不満を言う', 'word', 'うごき', null, null, true),
  ('3', 'concentrate', '集中する', 'word', 'うごき', null, null, true),
  ('3', 'consider', 'よく考える', 'word', 'うごき', null, null, true),
  ('3', 'continue', '続ける', 'word', 'うごき', null, null, true),
  ('3', 'copy', '写す、まねる', 'word', 'うごき', null, null, true),
  ('3', 'cover', 'おおう', 'word', 'うごき', null, null, true),
  ('3', 'create', '創り出す', 'word', 'うごき', null, null, true),
  ('3', 'depend', '頼る、〜しだいである', 'word', 'うごき', null, null, true),
  ('3', 'destroy', '破壊する', 'word', 'うごき', null, null, true),
  ('3', 'develop', '発達させる', 'word', 'うごき', null, null, true),
  ('3', 'die', '死ぬ', 'word', 'うごき', null, null, true),
  ('3', 'disappear', '消える', 'word', 'うごき', null, null, true),
  ('3', 'discover', '発見する', 'word', 'うごき', null, null, true),
  ('3', 'divide', '分ける', 'word', 'うごき', null, null, true),
  ('3', 'download', 'ダウンロードする', 'word', 'うごき', null, null, true),
  ('3', 'drive', '運転する', 'word', 'うごき', null, null, true),
  ('3', 'earn', 'かせぐ', 'word', 'うごき', null, null, true),
  ('3', 'encourage', 'はげます', 'word', 'うごき', null, null, true),
  ('3', 'exist', '存在する', 'word', 'うごき', null, null, true),
  ('3', 'expect', '予期する、期待する', 'word', 'うごき', null, null, true),
  ('3', 'explore', '探検する', 'word', 'うごき', null, null, true),
  ('3', 'fail', '失敗する', 'word', 'うごき', null, null, true),
  ('3', 'freeze', 'こおる', 'word', 'うごき', null, null, true),
  ('3', 'gather', '集まる、集める', 'word', 'うごき', null, null, true),
  ('3', 'graduate', '卒業する', 'word', 'うごき', null, null, true),
  ('3', 'hit', '打つ、ぶつかる', 'word', 'うごき', null, null, true),
  ('3', 'hug', 'だきしめる', 'word', 'うごき', null, null, true),
  ('3', 'improve', 'よくする、上達する', 'word', 'うごき', null, null, true),
  ('3', 'include', '含む', 'word', 'うごき', null, null, true),
  ('3', 'increase', '増える、増やす', 'word', 'うごき', null, null, true),
  ('3', 'invent', '発明する', 'word', 'うごき', null, null, true),
  ('3', 'land', '着陸する', 'word', 'うごき', null, null, true),
  ('3', 'lie', '横になる、うそをつく', 'word', 'うごき', null, null, true),
  ('3', 'manage', '管理する、なんとかやりとげる', 'word', 'うごき', null, null, true),
  ('3', 'marry', '結婚する', 'word', 'うごき', null, null, true),
  ('3', 'offer', '申し出る', 'word', 'うごき', null, null, true),
  ('3', 'order', '注文する、命令する', 'word', 'うごき', null, null, true),
  ('3', 'organize', '準備する、まとめる', 'word', 'うごき', null, null, true),
  ('3', 'pack', '荷造りする', 'word', 'うごき', null, null, true),
  ('3', 'pass', '通り過ぎる、合格する', 'word', 'うごき', null, null, true),
  ('3', 'perform', '演じる、演奏する', 'word', 'うごき', null, null, true),
  ('3', 'point', '指さす', 'word', 'うごき', null, null, true),
  ('3', 'pour', '注ぐ', 'word', 'うごき', null, null, true),
  ('3', 'predict', '予測する', 'word', 'うごき', null, null, true),
  ('3', 'prefer', '〜のほうを好む', 'word', 'うごき', null, null, true),
  ('3', 'pretend', 'ふりをする', 'word', 'うごき', null, null, true),
  ('3', 'prevent', '防ぐ', 'word', 'うごき', null, null, true),
  ('3', 'print', '印刷する', 'word', 'うごき', null, null, true),
  ('3', 'produce', '生産する', 'word', 'うごき', null, null, true),
  ('3', 'provide', '提供する', 'word', 'うごき', null, null, true),
  ('3', 'publish', '出版する', 'word', 'うごき', null, null, true),
  ('3', 'quit', 'やめる', 'word', 'うごき', null, null, true),
  ('3', 'raise', '上げる、育てる', 'word', 'うごき', null, null, true),
  ('3', 'reach', '届く、着く', 'word', 'うごき', null, null, true),
  ('3', 'realize', '気づく', 'word', 'うごき', null, null, true),
  ('3', 'record', '記録する、録音する', 'word', 'うごき', null, null, true),
  ('3', 'recycle', 'リサイクルする', 'word', 'うごき', null, null, true),
  ('3', 'regret', '後悔する', 'word', 'うごき', null, null, true),
  ('3', 'remind', '思い出させる', 'word', 'うごき', null, null, true),
  ('3', 'rent', '（お金を払って）借りる', 'word', 'うごき', null, null, true),
  ('3', 'replace', '取りかえる', 'word', 'うごき', null, null, true),
  ('3', 'satisfy', '満足させる', 'word', 'うごき', null, null, true),
  ('3', 'serve', '（食事を）出す', 'word', 'うごき', null, null, true),
  ('3', 'shine', 'かがやく', 'word', 'うごき', null, null, true),
  ('3', 'steal', 'ぬすむ', 'word', 'うごき', null, null, true),
  ('3', 'succeed', '成功する', 'word', 'うごき', null, null, true),
  ('3', 'suggest', '提案する', 'word', 'うごき', null, null, true),
  ('3', 'survive', '生き残る', 'word', 'うごき', null, null, true),
  ('3', 'swallow', '飲みこむ', 'word', 'うごき', null, null, true),
  ('3', 'trust', '信頼する', 'word', 'うごき', null, null, true),
  ('3', 'weigh', '重さがある、重さを量る', 'word', 'うごき', null, null, true),
  ('3', 'wander', '歩き回る', 'word', 'うごき', null, null, true),
  ('3', 'discuss', '話し合う', 'word', 'うごき', null, null, true),
  ('3', 'focus', '焦点を合わせる', 'word', 'うごき', null, null, true),
  ('3', 'judge', '判断する', 'word', 'うごき', null, null, true),
  ('3', 'let', '〜させる', 'word', 'うごき', null, null, true),
  ('3', 'mean', '意味する', 'word', 'うごき', null, null, true),
  ('3', 'pray', '祈る', 'word', 'うごき', null, null, true),
  ('3', 'set', '置く、（時計などを）合わせる', 'word', 'うごき', null, null, true),
  ('3', 'blow', '（風が）ふく', 'word', 'うごき', null, null, true),
  ('3', 'bend', '曲げる', 'word', 'うごき', null, null, true),
  ('3', 'sew', 'ぬう', 'word', 'うごき', null, null, true),
  ('3', 'tidy', '片づける', 'word', 'うごき', null, null, true),
  ('3', 'spell', 'つづる', 'word', 'うごき', null, null, true),
  ('3', 'attack', '攻撃する', 'word', 'うごき', null, null, true),
  ('3', 'contact', '連絡する', 'word', 'うごき', null, null, true),
  ('3', 'apply', '申しこむ', 'word', 'うごき', null, null, true),
  ('3', 'admit', '認める', 'word', 'うごき', null, null, true),
  ('3', 'oppose', '反対する', 'word', 'うごき', null, null, true),
  ('3', 'appreciate', 'ありがたく思う', 'word', 'うごき', null, null, true),
  ('3', 'impress', '感動させる', 'word', 'うごき', null, null, true),
  ('3', 'forbid', '禁じる', 'word', 'うごき', null, null, true),
  ('3', 'actually', '実は', 'word', 'ことば', null, null, true),
  ('3', 'ahead', '前方に', 'word', 'ことば', null, null, true),
  ('3', 'anyway', 'とにかく', 'word', 'ことば', null, null, true),
  ('3', 'badly', 'ひどく、悪く', 'word', 'ことば', null, null, true),
  ('3', 'besides', 'そのうえ', 'word', 'ことば', null, null, true),
  ('3', 'certainly', '確かに', 'word', 'ことば', null, null, true),
  ('3', 'clearly', 'はっきりと', 'word', 'ことば', null, null, true),
  ('3', 'correctly', '正しく', 'word', 'ことば', null, null, true),
  ('3', 'especially', '特に', 'word', 'ことば', null, null, true),
  ('3', 'exactly', 'ちょうど、まさに', 'word', 'ことば', null, null, true),
  ('3', 'extremely', '非常に', 'word', 'ことば', null, null, true),
  ('3', 'fortunately', '幸運にも', 'word', 'ことば', null, null, true),
  ('3', 'unfortunately', '不運にも', 'word', 'ことば', null, null, true),
  ('3', 'luckily', '運よく', 'word', 'ことば', null, null, true),
  ('3', 'hardly', 'ほとんど〜ない', 'word', 'ことば', null, null, true),
  ('3', 'however', 'しかしながら', 'word', 'ことば', null, null, true),
  ('3', 'indeed', '本当に、実に', 'word', 'ことば', null, null, true),
  ('3', 'instead', 'そのかわりに', 'word', 'ことば', null, null, true),
  ('3', 'mainly', '主に', 'word', 'ことば', null, null, true),
  ('3', 'mostly', 'たいていは', 'word', 'ことば', null, null, true),
  ('3', 'nearly', 'もう少しで', 'word', 'ことば', null, null, true),
  ('3', 'perhaps', 'ひょっとしたら', 'word', 'ことば', null, null, true),
  ('3', 'quietly', '静かに', 'word', 'ことば', null, null, true),
  ('3', 'quite', 'かなり', 'word', 'ことば', null, null, true),
  ('3', 'rather', 'むしろ、やや', 'word', 'ことば', null, null, true),
  ('3', 'seriously', '真剣に', 'word', 'ことば', null, null, true),
  ('3', 'simply', '単に', 'word', 'ことば', null, null, true),
  ('3', 'therefore', 'それゆえに', 'word', 'ことば', null, null, true),
  ('3', 'anymore', '（否定文で）もはや', 'word', 'ことば', null, null, true),
  ('3', 'forward', '前へ', 'word', 'ことば', null, null, true),
  ('3', 'loudly', '大声で', 'word', 'ことば', null, null, true),
  ('3', 'softly', 'やさしく、静かに', 'word', 'ことば', null, null, true),
  ('3', 'either', '（否定文で）〜もまた', 'word', 'ことば', null, null, true),
  ('3', 'else', 'ほかに', 'word', 'ことば', null, null, true),
  ('3', 'against', '〜に反対して', 'word', 'ことば', null, null, true),
  ('3', 'except', '〜を除いて', 'word', 'ことば', null, null, true),
  ('3', 'since', '〜以来', 'word', 'ことば', null, null, true),
  ('3', 'toward', '〜の方へ', 'word', 'ことば', null, null, true),
  ('3', 'out of', '〜から外へ', 'word', 'ことば', null, null, true),
  ('3', 'beyond', '〜をこえて', 'word', 'ことば', null, null, true),
  ('3', 'within', '〜以内に', 'word', 'ことば', null, null, true),
  ('3', 'as', '〜として', 'word', 'ことば', null, null, true),
  ('3', 'at', '〜で（場所・時刻）', 'word', 'ことば', null, null, true),
  ('3', 'a couple of ～', '２つの～、２，３の～', 'phrase', 'かず', 'I''ll be back in [[a couple of]] days.', '[[2、3]]日で戻るよ。', true),
  ('3', 'in time', '間に合って', 'phrase', 'じかん', 'We got to the station [[in time]].', '私たちは駅に[[間に合った]]。', true),
  ('3', 'think of ～', '～のことを考える、～を思いつく', 'phrase', 'うごき', 'I often [[think of]] my old friends.', '私はよく昔の友だちの[[ことを考える]]。', true),
  ('3', 'give up ～', '～をあきらめる', 'phrase', 'きもち', 'Don''t [[give up]] your dream.', '夢を[[あきらめ]]ないで。', true),
  ('3', 'get together', '集まる', 'phrase', 'かぞく・ひと', 'Let''s [[get together]] this weekend.', '今週末に[[集まろう]]。', true),
  ('3', 'calm down', '落ち着く', 'phrase', 'きもち', '[[Calm down]] and listen to me.', '[[落ち着いて]]、私の話を聞いて。', true),
  ('3', 'keep doing', '…し続ける', 'phrase', 'うごき', 'She [[kept running]] to the end.', '彼女は最後まで[[走り続けた]]。', true),
  ('3', 'make sure (～)', '（～を）確かめる', 'phrase', 'うごき', '[[Make sure]] the door is locked.', 'ドアにかぎがかかっているか[[確かめて]]。', true),
  ('3', 'get lost', '道に迷う', 'phrase', 'ばしょ', 'We [[got lost]] in the big city.', '私たちは大きな町で[[道に迷った]]。', true),
  ('3', 'ask for ～', '～を求める', 'phrase', 'うごき', 'He [[asked for]] some water.', '彼は水を[[ほしいと言った]]。', true),
  ('3', 'used to do', '以前は…したものだ', 'phrase', 'じかん', 'I [[used to]] live in Osaka.', '私は[[以前は]]大阪に住んでいた。', true),
  ('3', 'had better do', '…したほうがいい', 'phrase', 'ことば', 'You [[had better]] go to bed early.', '早くねた[[ほうがいい]]よ。', true),
  ('3', 'help A with B', 'AのBを手伝う', 'phrase', 'かぞく・ひと', 'My brother [[helped me with]] my homework.', '兄が私の宿題を[[手伝ってくれた]]。', true),
  ('3', 'after all', '結局、やっぱり', 'phrase', 'ことば', '[[After all]], we stayed home.', '[[結局]]、私たちは家にいた。', true),
  ('3', 'all the time', 'いつも', 'phrase', 'じかん', 'My dog sleeps [[all the time]].', 'うちの犬は[[いつも]]ねている。', true),
  ('3', 'all the way', 'ずっと、はるばる', 'phrase', 'ばしょ', 'He came [[all the way]] from Hokkaido.', '彼は北海道から[[はるばる]]来た。', true),
  ('3', '～ and so on', '～など', 'phrase', 'ことば', 'I bought eggs, milk, bread, [[and so on]].', 'たまご、牛乳、パン[[など]]を買った。', true),
  ('3', 'as ～ as possible', 'できるだけ～', 'phrase', 'ことば', 'Please come [[as soon as possible]].', '[[できるだけ早く]]来てください。', true),
  ('3', 'as usual', 'いつものように', 'phrase', 'じかん', '[[As usual]], she was late.', '[[いつものように]]、彼女はおくれた。', true),
  ('3', 'at least', '少なくとも', 'phrase', 'かず', 'Read [[at least]] one book a month.', '月に[[少なくとも]]1冊は本を読もう。', true),
  ('3', 'at once', 'すぐに', 'phrase', 'じかん', 'Come here [[at once]].', '[[すぐに]]ここに来なさい。', true),
  ('3', 'not ～ at all', 'まったく～ない', 'phrase', 'ことば', 'I don''t like spiders [[at all]].', '私はクモが[[まったく]]好きではない。', true),
  ('3', 'by hand', '手で', 'phrase', 'うごき', 'This sweater was made [[by hand]].', 'このセーターは[[手で]]作られた。', true),
  ('3', 'by mistake', 'まちがって', 'phrase', 'ことば', 'I took his umbrella [[by mistake]].', '私は[[まちがって]]彼のかさを持ってきた。', true),
  ('3', 'for a while', 'しばらくの間', 'phrase', 'じかん', 'Let''s rest [[for a while]].', '[[しばらく]]休もう。', true),
  ('3', 'in a hurry', '急いで', 'phrase', 'じかん', 'He left [[in a hurry]].', '彼は[[急いで]]出ていった。', true),
  ('3', 'in fact', '実際に、実は', 'phrase', 'ことば', '[[In fact]], I''ve never been abroad.', '[[実は]]、外国に行ったことがない。', true),
  ('3', 'in the end', '結局は、最後には', 'phrase', 'じかん', '[[In the end]], our team won.', '[[最後には]]、私たちのチームが勝った。', true),
  ('3', 'so far', '今までのところ', 'phrase', 'じかん', 'Everything is fine [[so far]].', '[[今のところ]]すべて順調だ。', true),
  ('3', 'these days', 'このごろ', 'phrase', 'じかん', 'I''m busy [[these days]].', '[[近ごろは]]いそがしい。', true),
  ('3', 'thanks to ～', '～のおかげで', 'phrase', 'きもち', '[[Thanks to]] you, I passed the test.', 'きみの[[おかげで]]、テストに合格した。', true),
  ('3', 'all over (～)', '（～の）いたる所で', 'phrase', 'ばしょ', 'This song is popular [[all over]] the world.', 'この歌は世界[[中で]]人気だ。', true),
  ('3', 'so ～ that …', 'とても～なので…', 'phrase', 'ことば', 'I was [[so tired that]] I went to bed early.', '[[とてもつかれていたので]]早くねた。', true),
  ('3', 'not only A but (also) B', 'AだけでなくBも', 'phrase', 'ことば', 'She speaks [[not only English but also French]].', '彼女は[[英語だけでなくフランス語も]]話す。', true),
  ('3', 'as soon as …', '…するとすぐに', 'phrase', 'じかん', 'Call me [[as soon as]] you get home.', '家に着い[[たらすぐに]]電話して。', true),
  ('3', 'Something is wrong with ～.', '～はどこか調子が悪い', 'phrase', 'もの', '[[Something is wrong with]] my bike.', '私の自転車は[[どこか調子が悪い]]。', true),
  ('3', 'right away', '今すぐ', 'phrase', 'じかん', 'I''ll do it [[right away]].', '[[今すぐ]]やるよ。', true),
  ('3', 'agree with ～', '（人・考え）に賛成する', 'phrase', 'きもち', 'I [[agree with]] you.', '私はきみ[[に賛成だ]]。', true),
  ('3', 'remember doing', '…したのを覚えている', 'phrase', 'きもち', 'I [[remember meeting]] him before.', '私は前に彼に[[会ったのを覚えている]]。', true),
  ('3', 'remember to do', '忘れずに…する', 'phrase', 'きもち', '[[Remember to]] bring your lunch.', '[[忘れずに]]お弁当を持ってきてね。', true),
  ('3', 'be tired of ～', '～にあきている', 'phrase', 'きもち', 'I''m [[tired of]] this game.', 'このゲームには[[あきた]]。', true),
  ('3', 'by now', '今ごろはもう', 'phrase', 'じかん', 'He should be home [[by now]].', '彼は[[今ごろはもう]]家にいるはずだ。', true),
  ('3', 'for now', '今のところは', 'phrase', 'じかん', 'That''s all [[for now]].', '[[今のところは]]これで全部です。', true),
  ('3', 'by chance', '偶然に', 'phrase', 'ことば', 'I met her [[by chance]] at the station.', '駅で[[偶然]]彼女に会った。', true),
  ('3', 'take part in ～', '～に参加する', 'phrase', 'あそび・スポーツ', 'I''ll [[take part in]] the speech contest.', '私はスピーチコンテスト[[に参加する]]。', true),
  ('3', 'look after ～', '～の世話をする', 'phrase', 'かぞく・ひと', 'Can you [[look after]] my cat?', '私のねこの[[世話をして]]くれる？', true),
  ('3', 'stay up', '（寝ないで）起きている', 'phrase', 'じかん', 'I [[stayed up]] late last night.', 'きのうの夜はおそくまで[[起きていた]]。', true),
  ('3', 'first of all', 'まず第一に', 'phrase', 'ことば', '[[First of all]], wash your hands.', '[[まず]]、手を洗いなさい。', true),
  ('3', 'at the moment', '今のところ、ちょうど今', 'phrase', 'じかん', 'He is busy [[at the moment]].', '彼は[[今]]いそがしい。', true),
  ('3', 'go out', '外出する', 'phrase', 'うごき', 'Let''s [[go out]] for dinner.', '夕食を食べに[[出かけよう]]。', true),
  ('3', 'be popular with ～', '～に人気がある', 'phrase', 'きもち', 'This game [[is popular with]] children.', 'このゲームは子どもたち[[に人気がある]]。', true),
  ('3', 'come true', '（夢などが）実現する', 'phrase', 'きもち', 'I hope your dream will [[come true]].', 'きみの夢が[[かなう]]といいね。', true),
  ('3', 'feel like doing', '…したい気がする', 'phrase', 'きもち', 'I [[feel like eating]] pizza.', 'ピザが[[食べたい気分だ]]。', true),
  ('3', 'one after another', '次々に', 'phrase', 'じかん', 'The guests arrived [[one after another]].', 'お客さんが[[次々に]]着いた。', true),
  ('3', 'every time …', '…するたびに', 'phrase', 'じかん', '[[Every time]] I see him, he smiles.', '彼に会う[[たびに]]、彼はほほえむ。', true),
  ('3', 'in order to do', '…するために', 'phrase', 'ことば', 'I study hard [[in order to]] pass the exam.', '試験に合格[[するために]]一生けんめい勉強する。', true),
  ('3', 'check out ～', '～を調べる、～を借り出す', 'phrase', 'うごき', 'I [[checked out]] three books from the library.', '図書館で本を3冊[[借りた]]。', true),
  ('3', 'hang up', '電話を切る', 'phrase', 'うごき', 'Don''t [[hang up]] yet.', 'まだ[[電話を切ら]]ないで。', true),
  ('3', 'give ～ a try', '～をためしてみる', 'phrase', 'きもち', 'It looks fun. Let''s [[give it a try]].', '楽しそう。[[ためしてみよう]]。', true),
  ('3', 'give ～ a hand', '～に手を貸す', 'phrase', 'かぞく・ひと', 'Can you [[give me a hand]]?', '[[手を貸して]]くれる？', true),
  ('3', 'call back', '折り返し電話する', 'phrase', 'うごき', 'I''ll [[call back]] later.', 'あとで[[折り返し電話します]]。', true),
  ('3', 'see ～ off', '～を見送る', 'phrase', 'かぞく・ひと', 'We [[saw her off]] at the airport.', '私たちは空港で彼女を[[見送った]]。', true),
  ('3', 'have no idea', '見当がつかない', 'phrase', 'きもち', 'I [[have no idea]] where he went.', '彼がどこへ行ったのか[[見当がつかない]]。', true),
  ('3', 'take one''s time', 'ゆっくりやる', 'phrase', 'じかん', '[[Take your time]]. We''re not in a hurry.', '[[ゆっくりでいいよ]]。急いでないから。', true),
  ('3', 'help oneself to ～', '～を自由に取って食べる', 'phrase', 'たべもの', 'Please [[help yourself to]] the cookies.', 'クッキーを[[ご自由にどうぞ]]。', true),
  ('3', 'be interested in ～', '～に興味がある', 'phrase', 'きもち', 'I''m [[interested in]] space.', '私は宇宙[[に興味がある]]。', true),
  ('3', 'be proud of ～', '～をほこりに思う', 'phrase', 'きもち', 'I''m [[proud of]] my team.', '私は自分のチームを[[ほこりに思う]]。', true),
  ('3', 'be surprised at ～', '～におどろく', 'phrase', 'きもち', 'We [[were surprised at]] the news.', '私たちはそのニュース[[におどろいた]]。', true),
  ('3', 'be full of ～', '～でいっぱいだ', 'phrase', 'いろ・ようす', 'The box [[is full of]] toys.', 'その箱はおもちゃ[[でいっぱいだ]]。', true),
  ('3', 'be late for ～', '～におくれる', 'phrase', 'じかん', 'Don''t [[be late for]] school.', '学校[[におくれ]]ないで。', true),
  ('3', 'I''m afraid not.', '残念ながらちがうと思います。', 'idiom', 'かいわ', '"Is she at home?" "[[I''m afraid not.]]"', '「彼女は家にいますか。」「[[残念ながらいません。]]」', true),
  ('3', 'You''re kidding.', '冗談でしょう。', 'idiom', 'かいわ', '"I won the lottery!" "[[You''re kidding.]]"', '「宝くじが当たった！」「[[冗談でしょう。]]」', true),
  ('3', 'What''s the matter?', 'どうしたの？', 'idiom', 'かいわ', '"[[What''s the matter?]]" "I lost my wallet."', '「[[どうしたの？]]」「さいふをなくしたんだ。」', true),
  ('3', 'That sounds like fun.', '楽しそうだね。', 'idiom', 'かいわ', '"Let''s go camping." "[[That sounds like fun.]]"', '「キャンプに行こう。」「[[楽しそうだね。]]」', true),
  ('3', 'May I take a message?', '伝言をうかがいましょうか。', 'idiom', 'かいわ', '"He''s out now. [[May I take a message?]]"', '「彼は今外出中です。[[伝言をうかがいましょうか。]]」', true),
  ('3', 'I''m just looking.', '見ているだけです。', 'idiom', 'かいわ', '"Can I help you?" "[[I''m just looking.]]"', '「いらっしゃいませ。」「[[見ているだけです。]]」', true),
  ('3', 'Why not?', 'もちろん、いいよ。', 'idiom', 'かいわ', '"Shall we go together?" "[[Why not?]]"', '「いっしょに行かない？」「[[もちろん。]]」', true),
  ('3', 'Help yourself.', 'ご自由にどうぞ。', 'idiom', 'かいわ', '"Can I have some cake?" "Sure. [[Help yourself.]]"', '「ケーキをもらってもいい？」「いいよ。[[ご自由にどうぞ。]]」', true),
  ('3', 'Take care.', '気をつけてね。', 'idiom', 'かいわ', '"I''m going home now." "OK. [[Take care.]]"', '「もう帰るね。」「うん。[[気をつけてね。]]」', true),
  ('3', 'Excuse me, but ～?', 'すみませんが、～？', 'idiom', 'かいわ', '"[[Excuse me, but]] could you take our picture?"', '「[[すみませんが]]、写真をとってもらえますか。」', true)
on conflict (level, en) do update set
  ja = excluded.ja, type = excluded.type, theme = excluded.theme,
  example_en = excluded.example_en, example_ja = excluded.example_ja, active = true;
commit;
